bootstrap-grafana-v10:
	cuebootstrap -inputs 'grafana-v10-samples/*.json' -skeleton bootstrap_config.cue -no-defaults > grafanaV10.cue

cuebootstrap-install:
	go install github.com/sivukhin/cuebootstrap/cmd/cuebootstrap@latest
