{
 "title": "DataBeaver Jobs",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "Job name",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"data-beaver-.*\"}, service_prometheus_track)"
    }
   },
   {
    "name": "job_name_no_domain",
    "query": {
     "query": "query_result(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-jobmanager\"}, \"job_no_domain\", \"$1-$2\", \"job\", \"(.*)-moj-(.*)-jobmanager\"))"
    }
   },
   {
    "name": "job_type",
    "label": "Job Type",
    "query": {
     "query": "label_values(flink_jobmanager_job_numRestarts{job=~\"([[job_name]])-jobmanager\"}, job_name)"
    }
   },
   {
    "name": "jobmanager_job",
    "label": "Job Manager Job Tag",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-jobmanager\"}, job)"
    }
   },
   {
    "name": "taskmanager_job",
    "label": "Task Manager Job Tag",
    "query": {
     "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-taskmanager\"}, job)"
    }
   },
   {
    "name": "version",
    "label": "Version",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-jobmanager\"}, job_version)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job=~\"$taskmanager_job\"},task_name)"
    }
   },
   {
    "name": "target",
    "label": "Target",
    "query": {
     "query": "query_result(count(flink_taskmanager_job_task_operator_processEvent_target_action_direction_result_total{job=~\"([[job_name]])-taskmanager\", target!=\"none\"}) by (target))\n"
    }
   },
   {
    "name": "redpanda_group",
    "label": "RP Consumer Group",
    "query": {
     "query": "label_values(redpanda_kafka_consumer_group_topics{redpanda_group=~\"^($job_name_no_domain)-.*\"},redpanda_group)"
    }
   },
   {
    "name": "redpanda_topic",
    "label": "RP Topic",
    "query": {
     "query": "label_values(redpanda_kafka_replicas{redpanda_topic !~ 'controller|group|__consumer_offsets', redpanda_topic !~ '^_.*|^__.*', redpanda_namespace=\"kafka\"}, redpanda_topic)"
    }
   },
   {
    "name": "redpanda_instance",
    "label": "RP Cluster",
    "query": "914dce73... : console-914dce73.ci8q04tu86fclp7lpl0g.byoc.prd.cloud.redpanda.com:443"
   },
   {
    "name": "aggr_criteria",
    "label": "RP Aggregate by",
    "query": "Topic : redpanda_topic, Topic\\, Partition : redpanda_topic\\,redpanda_partition"
   },
   {
    "name": "state_name",
    "label": "Job State name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"([[job_name]])-taskmanager\"}, state_name)"
    }
   },
   { "name": "timer_type", "query": "processing, event" },
   {
    "name": "source_task",
    "label": "Source Tasks",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job=~\"$taskmanager_job\", task_name=~\"Source.*\"},task_name)"
    }
   },
   {
    "name": "event_type",
    "label": "Event Type",
    "query": {
     "query": "query_result(count(flink_taskmanager_job_task_operator_processEvent_target_action_direction_result_total{job=~\"$taskmanager_job\"}) by (processEvent))"
    }
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flink Dashboard",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"$jobmanager_job\"}, \"dashboard\", \"http://$1.$2.$3.$4:8081\", \"host\", \"(.*)_(.*)_(.*)_(.*)\")) by (dashboard)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{job=~\"$jobmanager_job\"}",
     "legendFormat": "Registered {{job}}"
    },
    {
     "expr": "count(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Slots / TM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"} / flink_jobmanager_numRegisteredTaskManagers{job=~\"$jobmanager_job\"}"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"}",
     "legendFormat": "Total slots"
    },
    {
     "expr": "flink_jobmanager_taskSlotsAvailable{job=~\"$jobmanager_job\"}",
     "legendFormat": "Unused slots (should be 0)"
    }
   ]
  },
  {
   "title": "Avg Max Load [5m]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(max_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Task Subtasks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_job_task_numRecordsIn{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (job, task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Group Offset Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(redpanda_group) (max by(redpanda_namespace, redpanda_topic, redpanda_partition) (redpanda_kafka_max_offset{instance=~\"$redpanda_instance\", redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{instance=~\"$redpanda_instance\", redpanda_group=~\"[[redpanda_group]]\"})+1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total State Size (RockDB)",
   "type": "gauge",
   "description": "adding test explanation",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "SSTables: {{job}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Memtable: {{job}}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_Status_JVM_CPU_Load{job=~\"$jobmanager_job\"}) by (clustername)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Restarts ",
   "type": "stat",
   "description": "The total amount of full restarts of the job in the selected time period",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(flink_jobmanager_job_numRestarts{job=~\"$jobmanager_job\"}[30m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed records rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "RecIn/sec - {{job}} "
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by (job, job_version) or on(job) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m])) by (job, job_version) or on(job) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by (job, job_version)  or on(job) sum(rate(flink_taskmanager_job_task_operator_spanner_change_stream_reader_DataRecordCount{job=~\"$taskmanager_job\"})) by (job, job_version)",
     "legendFormat": "Kafka/PubSub/CDC - {{job}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 7d) by (job, job_version) or on(job) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m] offset 7d)) by (job, job_version) or on(job) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 7d) by (job, job_version)  or on(job) sum(rate(flink_taskmanager_job_task_operator_spanner_change_stream_reader_DataRecordCount{job=~\"$taskmanager_job\"} offset 7d)) by (job, job_version)",
     "legendFormat": "Kafka/PubSub/CDC-7d - {{job}}"
    }
   ]
  },
  {
   "title": "Day-to-Day Processed Records Rate Change",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by(job) or on(job) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m])) or on(job) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"})  by (job) or on() vector(0)) / on(job) (sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 1d) by(job) or on(job) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m] offset 1d)) by (job) or on(job) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 1d) by (job) or on() vector(1))"
    }
   ]
  },
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Task Managers",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Running - {{job}}"
    },
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{job=~\"$taskmanager_job\"}",
     "legendFormat": "Registered - {{job}}"
    },
    {
     "expr": "sum(increase(flink_jobmanager_job_numRestarts{job=~\"$jobmanager_job\"}[1m])) by (job)",
     "legendFormat": "Restarts (right-y) - {{job}}"
    }
   ]
  },
  {
   "title": "Memory [AVG]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "avg(avg_over_time(flink_taskmanager_Status_Flink_Memory_Managed_Used{job=\"$taskmanager_job\"}[5m])) by (job)",
     "legendFormat": "Flink Managed Avg Used (GB) - {{job}}"
    },
    {
     "expr": "sum(\n    avg_over_time(flink_taskmanager_Status_Flink_Memory_Managed_Used{job=\"$taskmanager_job\"}[5m])\n) by (job) \n    / \nsum(\n    avg_over_time(flink_taskmanager_Status_Flink_Memory_Managed_Total{job=\"$taskmanager_job\"}[5m])\n)  by (job)",
     "legendFormat": "Flink Managed Avg Used (%) - {{job}}"
    },
    {
     "expr": "sum(\n    avg_over_time(flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{job=\"$taskmanager_job\"}[5m])\n) by (job) \n    / \nsum(\n    avg_over_time(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{job=\"$taskmanager_job\"}[5m])\n)  by (job)",
     "legendFormat": "JVM Direct Avg Used - {{job}}"
    },
    {
     "expr": "sum(\n    avg_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"$taskmanager_job\"}[5m])\n) by (job) \n    / \nsum(\n    avg_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Max{job=\"$taskmanager_job\"}[5m])\n)  by (job)",
     "legendFormat": "JVM Heap Avg Used - {{job}}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "TM: {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "Average - {{job}}"
    },
    {
     "expr": "avg(sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m] offset 1d)) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "Average y - {{job}}"
    }
   ]
  },
  {
   "title": "Memory [MAX]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(\n    max_over_time(flink_taskmanager_Status_Flink_Memory_Managed_Used{job=\"$taskmanager_job\"}[5m])\n) by (job) \n    / \nsum(\n    max_over_time(flink_taskmanager_Status_Flink_Memory_Managed_Total{job=\"$taskmanager_job\"}[5m])\n)  by (job)",
     "legendFormat": "Flink Managed Max Used (%) - {{job}}"
    },
    {
     "expr": "sum(\n    max_over_time(flink_taskmanager_Status_JVM_Memory_Direct_MemoryUsed{job=\"$taskmanager_job\"}[5m])\n) by (job) \n    / \nsum(\n    max_over_time(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{job=\"$taskmanager_job\"}[5m])\n)  by (job)",
     "legendFormat": "JVM Direct Max Used - {{job}}"
    },
    {
     "expr": "sum(\n    max_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"$taskmanager_job\"}[5m])\n) by (job) \n    / \nsum(\n    max_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Max{job=\"$taskmanager_job\"}[5m])\n)  by (job)",
     "legendFormat": "JVM Heap Max Used - {{job}}"
    }
   ]
  },
  {
   "title": "Task Slots",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"} - flink_jobmanager_taskSlotsAvailable{job=~\"$jobmanager_job\"}) by (job)",
     "legendFormat": "Used Slots - {{job}}"
    },
    {
     "expr": "sum(flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"}) by (job)",
     "legendFormat": "Total Slots - {{job}}"
    }
   ]
  },
  {
   "title": "CPU Throttling [MAX]",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "max(max_over_time(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"apache-flink\", pod=~\"$job_name.*\"}[1m])[5m]))",
     "legendFormat": "CPU Throttling - {{job}}"
    },
    {
     "expr": "max(max_over_time(rate(container_cpu_cfs_throttled_seconds_total{namespace=\"apache-flink\", pod=~\"$job_name.*\"}[1m] offset 1d)[5m]))",
     "legendFormat": "CPU Throttling - y"
    }
   ]
  },
  {
   "title": "Targets Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 },
   "collapsed": true,
   "panels": [
    {
     "title": "$event_type Source (rate [1m])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 46 },
     "repeat": "event_type",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_processEvent_target_action_direction_result_total{processEvent=~\"$event_type\", target=\"none\", job=~\"$taskmanager_job\"}[1m])) by (processEvent, action, direction, result)",
       "legendFormat": "{{processEvent}}-{{action}}-{{direction}}-{{result}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_processEvent_target_action_direction_result_output_total{processEvent=~\"$event_type\", target=\"none\", job=~\"$taskmanager_job\", direction=\"output\"}[1m])) by (processEvent, action, result, output)",
       "legendFormat": "{{processEvent}}-{{action}}-output-{{result}}-{{output}}"
      }
     ]
    },
    {
     "title": "$event_type Invalid (rate [1m])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 46 },
     "repeat": "event_type",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_processEvent_target_action_invalidEvent_total{job=~\"$taskmanager_job\", processEvent=~\"$event_type\"}[1m])) by (processEvent, action, invalidEvent)",
       "legendFormat": "{{processEvent}}-{{action}}-{{invalidEvent}}"
      }
     ]
    },
    {
     "title": "$target Target (rate[1m])",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 46 },
     "repeat": "target",
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_processEvent_target_action_direction_result_total{target=\"$target\", job=~\"$taskmanager_job\"}[1m])) by (processEvent, action, direction, result)",
       "legendFormat": "{{processEvent}}-{{action}}-{{direction}}-{{result}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_processEvent_target_action_direction_result_output_total{target=\"$target\", job=~\"$taskmanager_job\", direction=\"output\"}[1m])) by (processEvent, action, result, output)",
       "legendFormat": "{{processEvent}}-{{action}}-output-{{result}}-{{output}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Join Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 },
   "collapsed": true,
   "panels": [
    {
     "title": "Join Events Rate [10s] by (Op, Event)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_batchJoin_ProcessEvent_total{job=\"$taskmanager_job\"})[10s]) by (operator_name, batchJoin_ProcessEvent)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "avg(p95(batchSize)) by (Op, Type)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_batchJoin_batchSize_hist{job=\"$taskmanager_job\", quantile=\"0.95\"}) by (operator_name, batchJoin_batchSize)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Joined Records Key Rate [5m] by (Op, Key)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_batchJoin_JoinedRecords_Key_total{job=\"$taskmanager_job\"})[5m]) by (operator_name, batchJoin_JoinedRecords_Key)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Join Left Lag (p-avg) [5m] by (Op)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_batchJoin_RightInterval{job=~\"$taskmanager_job\", quantile=\"0.999\"}) by (operator_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name, kubernetes_pod_name)) by (operator_name) / sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name)",
       "legendFormat": "p999-Left Lag-{{operator_name}}"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_batchJoin_RightInterval{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (operator_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name, kubernetes_pod_name)) by (operator_name) / sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name)",
       "legendFormat": "p99-Left Lag-{{operator_name}}"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_batchJoin_RightInterval{job=~\"$taskmanager_job\", quantile=\"0.95\"}) by (operator_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name, kubernetes_pod_name)) by (operator_name) / sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name)",
       "legendFormat": "p95-Left Lag-{{operator_name}}"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_batchJoin_RightInterval{job=~\"$taskmanager_job\", quantile=\"0.75\"}) by (operator_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name, kubernetes_pod_name)) by (operator_name) / sum(rate(flink_taskmanager_job_task_operator_batchJoin_RightInterval_count{job=~\"$taskmanager_job\"}[5m])) by (operator_name)",
       "legendFormat": "p75-Left Lag-{{operator_name}}"
      }
     ]
    },
    {
     "title": "Join Saved Rate [5m] by (Op, Key)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_batchJoin_SavedRecords_total{job=\"$taskmanager_job\"})[10s]) by (operator_name, batchJoin_SavedRecords)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "State Cleanup Rate [5m] by (Op, StateName)",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 46 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_batchJoin_StateCleanup_total{job=\"$taskmanager_job\"})[5m]) by (operator_name, batchJoin_StateCleanup)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flink Source Total Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job=~\"$taskmanager_job\"} >= 0) by (job, operator_name)",
       "legendFormat": "Lag - {{operator_name}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_pendingRecords{job=~\"$taskmanager_job\"} >= 0) by (job, operator_name)",
       "legendFormat": "Pending - {{operator_name}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job=~\"$taskmanager_job\"} >= 0) by (job)",
       "legendFormat": "Total lag - {{job}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_pendingRecords{job=~\"$taskmanager_job\"} >= 0) by (job)",
       "legendFormat": "Total Pending - {{job}}"
      }
     ]
    },
    {
     "title": "RP Consumer Group Offset Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by(redpanda_group) (max by(redpanda_namespace, redpanda_topic, redpanda_partition) (redpanda_kafka_max_offset{instance=~\"$redpanda_instance\", redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{instance=~\"$redpanda_instance\", redpanda_group=~\"[[redpanda_group]]\"})+1)",
       "legendFormat": "Group: {{redpanda_group}}, Topic: {{redpanda_topic}}, Partition: {{redpanda_partition}}"
      }
     ]
    },
    {
     "title": "Offset Lag (seconds)",
     "type": "stat",
     "description": "Only applies when topics are being written to (to understand the write-rate and compute the offset against that)",
     "gridPos": { "h": 8, "w": 4, "x": 20, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "avg\n(\n    (max by(redpanda_namespace, redpanda_topic, redpanda_partition)(redpanda_kafka_max_offset{instance=~\"$redpanda_instance\", redpanda_namespace=\"kafka\", redpanda_topic!=\"__consumer_offsets\"}) - on (redpanda_topic, redpanda_partition) group_right max by(redpanda_group,redpanda_topic, redpanda_partition) (redpanda_kafka_consumer_group_committed_offset{instance=~\"$redpanda_instance\", redpanda_group=~\"[[redpanda_group]]\",redpanda_topic=~\"[[redpanda_topic]]\"})\n    )\n    / on (redpanda_topic, redpanda_partition) group_right\n    max by(redpanda_namespace, redpanda_topic, redpanda_partition) (rate(redpanda_kafka_max_offset{instance=~\"$redpanda_instance\", redpanda_topic=~\"[[redpanda_topic]]\"}[$__rate_interval])!=0) \n)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Consumed Rate, Bytes/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{job=~\"$taskmanager_job\"}) by (operator_name)"
      }
     ]
    },
    {
     "title": "Consumed Rate, Records/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by (operator_name)"
      }
     ]
    },
    {
     "title": "Quartile Watermark Lag: $source_task",
     "type": "timeseries",
     "description": "p75 and p25 of the watermark lag for $source_task task\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
     "repeat": "source_task",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "quantile(0.75, flink_taskmanager_job_task_operator_watermarkLag{job=~\"$taskmanager_job\", task_name=\"$source_task\"}) by (task_name, job_name)",
       "legendFormat": "P75-{{task_name}} - {{job_name}}"
      },
      {
       "expr": "quantile(0.25, flink_taskmanager_job_task_operator_watermarkLag{job=~\"$taskmanager_job\", task_name=\"$source_task\"}) by (task_name, job_name)",
       "legendFormat": "P25-{{task_name}} - {{job_name}}"
      }
     ]
    },
    {
     "title": "Assigned Partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 88 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_assigned_partitions{job=~\"$taskmanager_job\"}) by (operator_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Kafka Fetch Max Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 88 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_fetch_latency_max{job=~\"$taskmanager_job\"}) by (operator_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Producer",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_error_total{job=~\"$taskmanager_job\"}))",
       "legendFormat": "error"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{job=~\"$taskmanager_job\"}))",
       "legendFormat": "records"
      }
     ]
    },
    {
     "title": "Avg Send Time",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 96 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "quantile(0.99, avg(flink_taskmanager_job_task_operator_currentSendTime{job=\"$taskmanager_job\"}) by (subtask_index))",
       "legendFormat": "p99(avg(currentSendTime))"
      },
      {
       "expr": "quantile(0.5, avg(flink_taskmanager_job_task_operator_currentSendTime{job=\"$taskmanager_job\"}) by (subtask_index))",
       "legendFormat": "p50(avg(currentSendTime))"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last checkpoint duration",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointDuration{job=\"$jobmanager_job\"}",
       "legendFormat": "{{job_name}}-{{job_id}}"
      }
     ]
    },
    {
     "title": "Last checkpoint Size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "flink_jobmanager_job_lastCheckpointSize{job=\"$jobmanager_job\"}",
       "legendFormat": "{{job_name}}-{{job_id}}"
      }
     ]
    },
    {
     "title": "Max checkpoint alignment time by task",
     "type": "timeseries",
     "description": "The maximum time spent waiting to align checkpoints per task.",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "max(flink_taskmanager_job_task_checkpointAlignmentTime{job=\"$taskmanager_job\"} > 0) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    },
    {
     "title": "Max checkpoint start delay time by task",
     "type": "timeseries",
     "description": "The maximum time spent waiting to start checkpointing per task.",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "max(flink_taskmanager_job_task_checkpointStartDelayNanos{job=\"$taskmanager_job\"} > 0) by (task_name)",
       "legendFormat": "{{task_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager  (Job Task - General)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 49 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subtasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "count(flink_taskmanager_job_task_numRecordsIn{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (job, task_name, task_id)",
       "legendFormat": "{{task_name}} ({{task_id}})"
      }
     ]
    },
    {
     "title": "Avg Back Pressure ms/sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (clustername, task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Avg Busy ms/sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_busyTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m]) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Avg Idle Time ms/sec",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_idleTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Avg Number Buffers in Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_numBuffersInLocalPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"} + flink_taskmanager_job_task_numBuffersInRemotePerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Avg Number Buffers Out Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 23 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_numBuffersOutPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Number Records In Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_numRecordsInPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Number Records Out Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_numRecordsOutPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Input Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_buffers_inputQueueLength{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Output Queue Length",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_buffers_outputQueueLength{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "In Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 51 },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_buffers_inPoolUsage{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    },
    {
     "title": "Out Pool Usage",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 51 },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_buffers_outPoolUsage{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (task_name, task_id)",
       "legendFormat": "{{[[by]]}} {{task_name}} {{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Task Manager (Watermarks)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 50 },
   "collapsed": true,
   "panels": [
    {
     "title": "Kafka Source Output Watermark",
     "type": "timeseries",
     "description": "Watermark per source operator",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "quantile(0.99, flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\"Source.*\"} >= 0) by (operator_name, task_id)",
       "legendFormat": "p99-{{operator_name}} Task: {{task_id}}"
      },
      {
       "expr": "quantile(0.5, flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\"Source.*\"} >= 0) by (operator_name, task_id)",
       "legendFormat": "p50-{{operator_name}} Task: {{task_id}}"
      },
      {
       "expr": "quantile(0.01, flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\"Source.*\"} >= 0) by (operator_name, task_id)",
       "legendFormat": "p01-{{operator_name}} Task: {{task_id}}"
      }
     ]
    },
    {
     "title": "$task_name Operators Input Watermark",
     "type": "timeseries",
     "description": "Minimum watermark per task across all subtasks and attempts",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 31 },
     "repeat": "task_name",
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_currentInputWatermark{job=~\"$taskmanager_job\", task_name=~\"$task_name\", operator_name!=\".*Join.*\"}",
       "legendFormat": "{{operator_name}}, Attempt: {{task_attempt_num}}-{{subtask_index}}"
      }
     ]
    },
    {
     "title": "$task_name Operators Output Watermark",
     "type": "timeseries",
     "description": "Output watermark across all operator subtasks and attempts",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 31 },
     "repeat": "task_name",
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", task_name=~\"$task_name\", operator_name!=\".*Kafka.*\"}",
       "legendFormat": "{{operator_name}} Attempt: {{subtask_index}}-{{task_attempt_num}}"
      }
     ]
    },
    {
     "title": "Watermark Alignment Drift",
     "type": "timeseries",
     "description": "The current drift from the minimal watermark emitted of all tasks belonging to the same watermark group. ",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_watermarkAlignmentDrift{job=~\"$taskmanager_job\"} >= -6.048e+8",
       "legendFormat": "{{operator_name}}-{{task_name}}-{{subtask_index}}-{{task_attempt_num}}"
      },
      {
       "expr": "min(flink_taskmanager_job_task_operator_watermarkAlignmentDrift{job=~\"$taskmanager_job\"} >= -6.048e+8) by (task_name, operator_name)",
       "legendFormat": "MIN-{{operator_name}}-{{task_name}}"
      }
     ]
    },
    {
     "title": "Join Operator Input Watermark",
     "type": "timeseries",
     "description": "Input watermarks for join operator across all task attempts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "targets": [
      {
       "expr": "topk(1, flink_taskmanager_job_task_operator_currentInput1Watermark{job=~\"$taskmanager_job\", operator_name=~\".*Join.*\"}) by (task_attempt_num)",
       "legendFormat": "Input1-{{operator_name}}, Attempt: {{task_attempt_num}}-{{subtask_index}} Task: {{task_id}}"
      },
      {
       "expr": "topk(1, flink_taskmanager_job_task_operator_currentInput2Watermark{job=~\"$taskmanager_job\", operator_name=~\".*Join.*\"}) by (task_attempt_num)",
       "legendFormat": "Input2-{{operator_name}}, Attempt: {{task_attempt_num}}-{{subtask_index}} Task: {{task_id}}"
      },
      {
       "expr": "topk(1, flink_taskmanager_job_task_operator_currentInputWatermark{job=~\"$taskmanager_job\", operator_name=~\".*Join.*\"}) by (task_attempt_num)",
       "legendFormat": "{{operator_name}}, Attempt: {{task_attempt_num}}-{{subtask_index}} Task: {{task_id}}"
      }
     ]
    },
    {
     "title": "Join Operator Output Watermark",
     "type": "timeseries",
     "description": "Output watermark for join operator across all task attempts",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "dateTimeAsIsoNoDateIfToday" } },
     "targets": [
      {
       "expr": "flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\".*Join.*\"} >= 0",
       "legendFormat": "{{operator_name}}, Attempt: {{task_attempt_num}}-{{subtask_index}} Task: {{task_id}}"
      }
     ]
    },
    {
     "title": "Kafka Write/Commit Operator Output Watermark Age",
     "type": "timeseries",
     "description": "Watermark per Kafka commit operator\n",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 63 },
     "fieldConfig": { "defaults": { "unit": "dateTimeFromNow" } },
     "targets": [
      {
       "expr": "quantile(0.01, flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\".*Kafka.*\"} >= 0) by (operator_name, task_id)",
       "legendFormat": "p01-{{operator_name}}, Task: {{task_id}}"
      },
      {
       "expr": "quantile(0.5, flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\".*Kafka.*\"} >= 0) by (operator_name, task_id)",
       "legendFormat": "p50-{{operator_name}}, Task: {{task_id}}"
      },
      {
       "expr": "quantile(0.99, flink_taskmanager_job_task_operator_currentOutputWatermark{job=~\"$taskmanager_job\", operator_name=~\".*Kafka.*\"} >= 0) by (operator_name, task_id)",
       "legendFormat": "p99-{{operator_name}}, Task: {{task_id}}"
      }
     ]
    }
   ]
  },
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 51 },
   "collapsed": true,
   "panels": [
    {
     "title": "State Read Access Latencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateGetLatency ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStateGetLatency({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_listStateGetLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_listStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ListStateGetLatency ({{state_name}})"
      }
     ]
    },
    {
     "title": "State Read Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStateGetRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateGetRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ListStateGetRate ({{state_name}})"
      }
     ]
    },
    {
     "title": "State Write Access Latencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateUpdateLatency ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutAllLatency  ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutLatency ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_listStateAddLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateAddLatency_count{job=\"$taskmanager_job\"}[1m])) by (state_name, kubernetes_pod_name)) by (state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_listStateAddLatency_count{job=\"$taskmanager_job\"}[1m])) by (state_name)",
       "legendFormat": "ListStateAddLatency ({{state_name}})"
      }
     ]
    },
    {
     "title": "State Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateUpdateRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutAllRate ({{state_name}}"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateAddLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ListStateAddRate ({{state_name}})"
      }
     ]
    },
    {
     "title": "Active Compactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_num_running_compactions{job=\"$taskmanager_job\"}) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total State Size (RockDB)",
     "type": "timeseries",
     "description": "adding test explanation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "{{job}}: SSTables"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "{{job}}: Memtable"
      }
     ]
    },
    {
     "title": "Active Flushes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_num_running_flushes{job=\"$taskmanager_job\"}) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Max State Size Per Task Manager (RockDB)",
     "type": "timeseries",
     "description": "adding test explanation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "max(sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job, kubernetes_pod_name)) by (job)",
       "legendFormat": "{{job}}: SSTables"
      },
      {
       "expr": "max(sum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}) by (job, kubernetes_pod_name)) by (job)",
       "legendFormat": "{{job}}: Memtable"
      }
     ]
    }
   ]
  },
  {
   "title": "Auto Scaler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "panels": [
    {
     "title": "Vertex Scale Down",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "targets": [
      {
       "expr": "flink_k8soperator_namespace_resource_AutoScaler_jobVertexID_SCALE_DOWN_RATE_THRESHOLD_Current{resourcename=\"moj_${job_type}\"} - flink_k8soperator_namespace_resource_AutoScaler_jobVertexID_TRUE_PROCESSING_RATE_Average{resourcename=\"moj_${job_type}\"}",
       "legendFormat": "{{jobVertexID}} - (scale down - true avg)"
      }
     ]
    },
    {
     "title": "Vertex Scale Up",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "targets": [
      {
       "expr": "flink_k8soperator_namespace_resource_AutoScaler_jobVertexID_TRUE_PROCESSING_RATE_Average{resourcename=\"moj_${job_type}\"} - flink_k8soperator_namespace_resource_AutoScaler_jobVertexID_SCALE_UP_RATE_THRESHOLD_Current{resourcename=\"moj_${job_type}\"}",
       "legendFormat": "{{jobVertexID}} - (true avg - scale up)"
      }
     ]
    },
    {
     "title": "Additional Parallelism",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "flink_k8soperator_namespace_resource_AutoScaler_jobVertexID_RECOMMENDED_PARALLELISM_Current{resourcename=\"moj_${job_type}\"} - \nflink_k8soperator_namespace_resource_AutoScaler_jobVertexID_PARALLELISM_Current{resourcename=\"moj_${job_type}\"}",
       "legendFormat": "{{jobVertexID}} -- (recommended - current)"
      }
     ]
    }
   ]
  },
  {
   "title": "Timers",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "panels": [
    {
     "title": "$timer_type Timer Ops",
     "type": "timeseries",
     "description": "trigger counter is offset by 10m from the future",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "repeat": "timer_type",
     "fieldConfig": { "defaults": { "unit": "opm" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_timerType_op_total{job=\"${job_name}-taskmanager\", timerType=~\"$timer_type\", op!=\"trigger\"}[1m])) by (op)",
       "legendFormat": "__auto"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_timerType_op_total{job=\"${job_name}-taskmanager\", timerType=~\"$timer_type\", op=\"trigger\"}[1m])) by (op)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimate RocksDb Keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_num_keys{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "{{column_family}}-{{job}}"
      }
     ]
    },
    {
     "title": "Estimate RocksDb Data Size",
     "type": "timeseries",
     "description": "total.sst.files.size + size.all.mem-tables",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}[1m]) by (column_family, job) \n+\nsum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}[1m]) by (column_family, job)",
       "legendFormat": "{{column_family}}-{{job}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_capacity{job=\"$taskmanager_job\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage{job=\"$taskmanager_job\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_pinned_usage{job=\"$taskmanager_job\"})",
       "legendFormat": "Pinned"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache Usage [1m] by Operator",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_hit{job=~\"$taskmanager_job\"})[1m]) by (operator_name)",
       "legendFormat": "Cache Hit: {{operator_name}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_block_cache_miss{job=~\"$taskmanager_job\"})[1m]) by (operator_name)",
       "legendFormat": "Cache Miss: {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Bytes Read Rate [5m] by Operator",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 12, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_bytes_read{job=~\"$taskmanager_job\"})[1m]) by (operator_name)",
       "legendFormat": "Get - {{operator_name}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_iter_bytes_read{job=~\"$taskmanager_job\"})[1m]) by (operator_name)",
       "legendFormat": "Iter - {{operator_name}}"
      }
     ]
    },
    {
     "title": "RocksDB Bytes Written Rate [5m] by Operator",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 18, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_bytes_written{job=~\"$taskmanager_job\"})[1m]) by (operator_name)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Estimate Pending Compaction Bytes Rate [1m] ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_pending_compaction_bytes{job=~\"$taskmanager_job\"}[1m])) by (column_family)",
       "legendFormat": "{{column_family}}"
      }
     ]
    },
    {
     "title": "Compaction Read Bytes Rate [1m] ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_compact_read_bytes{job=~\"$taskmanager_job\"}[1m])) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "Compaction Written Bytes Rate [1m] ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_compact_write_bytes{job=~\"$taskmanager_job\"}[1m])) by (operator_name)",
       "legendFormat": "{{operator_name}}"
      }
     ]
    },
    {
     "title": "Is Write Stopped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_column_family_rocksdb_is_write_stopped{job=~\"$taskmanager_job\"}[1m]) by (column_family, job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Delayed Write Rate & Operator Stalls",
     "type": "timeseries",
     "description": "Stall micros - the duration of writer requiring to wait for compaction or flush to finish in RocksDB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_actual_delayed_write_rate{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Delayed Write Rate - {{column_family}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_stall_micros{job=~\"$taskmanager_job\"}[1m])) by (operator_name, job)",
       "legendFormat": "Stall - {{operator_name}} (micros)"
      }
     ]
    },
    {
     "title": "Active Memtable Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Entries - {{column_family}}"
      }
     ]
    },
    {
     "title": "Active Memtable Deletes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Deletes - {{column_family}}"
      }
     ]
    },
    {
     "title": "Active Memtable Delete Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)\n/\nsum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Deletes ratio - {{column_family}}"
      }
     ]
    },
    {
     "title": "Unflushed Memtables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_num_immutable_mem_table{job=~\"$taskmanager_job\"}[1m]) by (job)",
       "legendFormat": "Unflushed - {{job}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_mem_table_flush_pending{job=~\"$taskmanager_job\"}[1m]) by (job)",
       "legendFormat": "Flush pending - {{job}}"
      }
     ]
    },
    {
     "title": "Unflushed Memtable Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 83 },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_imm_mem_tables{job=~\"$taskmanager_job\"}[1m])) by (job)",
       "legendFormat": "Entries - {{job}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_imm_mem_tables{job=~\"$taskmanager_job\"}[1m])) by (job)",
       "legendFormat": "Deletes - {{job}}"
      }
     ]
    }
   ]
  }
 ]
}