{
 "title": "Go universal dashboard [cuemon]",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "cluster_name",
    "label": "cluster_name",
    "query": {
     "query": "label_values(go_info,clustername)"
    }
   },
   {
    "name": "service_prometheus_track",
    "label": "service_prometheus_track",
    "query": {
     "query": "label_values(go_info{clustername=\"$cluster_name\"},service_prometheus_track)"
    }
   },
   { "name": "func", "label": "func", "query": "avg,max" },
   {
    "name": "by",
    "label": "by",
    "query": "service_prometheus_track,kubernetes_pod_name,zone,node_instance_type,id"
   },
   { "name": "show_yesterday", "label": "show_yesterday", "query": "hide,show" }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Go version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(go_info{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}) by (service_prometheus_track, version)",
     "legendFormat": "{{ service_prometheus_track }} - {{ version }}"
    }
   ]
  },
  {
   "title": "Pods count",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(sum(go_info{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}) by (service_prometheus_track, kubernetes_pod_name)) by (service_prometheus_track)",
     "legendFormat": "{{ service_prometheus_track }}"
    }
   ]
  },
  {
   "title": "Heap size (average)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$func(go_memstats_heap_alloc_bytes{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}) by (service_prometheus_track)",
     "legendFormat": "{{ service_prometheus_track }}"
    }
   ]
  },
  {
   "title": "Goroutine scheduling latency (p999)",
   "type": "stat",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "$func(histogram_quantile(0.999, sum(rate(go_sched_latencies_seconds_bucket{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m])) by (le, kubernetes_pod_name, service_prometheus_track))) by (service_prometheus_track)",
     "legendFormat": "{{ service_prometheus_track }}"
    }
   ]
  },
  { "title": "Details", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Heap size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "$func(go_memstats_heap_alloc_bytes{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(go_memstats_heap_alloc_bytes{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Heap objects",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$func(go_memstats_heap_objects{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(go_memstats_heap_objects{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Next GC trigger size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "$func(go_memstats_next_gc_bytes{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(go_memstats_next_gc_bytes{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Threads",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$func(go_threads{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(go_threads{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Goroutines",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$func(go_goroutines{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(go_goroutines{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "GC pauses latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "$func(rate(go_gc_pauses_seconds_sum{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h)) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(rate(go_gc_pauses_seconds_sum{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h)) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Goroutine scheduling latency (p99)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$func(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h)) by (le, kubernetes_pod_name, ${by}))) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h)) by (le, kubernetes_pod_name, ${by}))) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Goroutine scheduling latency (p999)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$func(histogram_quantile(0.999, sum(rate(go_sched_latencies_seconds_bucket{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h)) by (le, kubernetes_pod_name, ${by}))) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(histogram_quantile(0.999, sum(rate(go_sched_latencies_seconds_bucket{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h)) by (le, kubernetes_pod_name, ${by}))) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  },
  {
   "title": "Sync mutex wait",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 78 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "$func(rate(go_sync_mutex_wait_total_seconds_total{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 0h)) by (${by})",
     "legendFormat": "{{ $by }}"
    },
    {
     "expr": "$func(rate(go_sync_mutex_wait_total_seconds_total{clustername=\"$cluster_name\", service_prometheus_track=~\"^${service_prometheus_track:pipe}$\"}[1m] offset 24h)) by (${by})",
     "legendFormat": "{{ $by }} - yesterday($show_yesterday)"
    }
   ]
  }
 ]
}