{
 "title": "K8s Deployment Topology",
 "description": "Explore how K8s Deployment pods are distributed across various dimensions (zone, node provisioning type, etc.)",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Cluster",
    "query": {
     "query": "label_values(kube_node_info{}, clustername)"
    }
   },
   {
    "name": "Namespace",
    "query": {
     "query": "label_values(kube_pod_labels{clustername=\"$Cluster\"}, namespace)"
    }
   },
   {
    "name": "FilterBy",
    "query": "DeploymentId : label_id,App : label_app,Service : label_service"
   },
   {
    "name": "DeploymentId",
    "query": {
     "query": "label_values(kube_pod_labels{clustername=\"$Cluster\", namespace=\"$Namespace\"}, label_id)"
    }
   },
   {
    "name": "App",
    "query": {
     "query": "label_values(kube_pod_labels{clustername=\"$Cluster\", namespace=\"$Namespace\"}, label_app)"
    }
   },
   {
    "name": "Service",
    "query": {
     "query": "label_values(kube_pod_labels{clustername=\"$Cluster\", namespace=\"$Namespace\"}, label_service)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true
  },
  { "title": "Filter by DeploymentId", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Pods distribution by GCP zone",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "expr": "sum by (label_zone) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_id=\"$DeploymentId\"})",
     "legendFormat": "{{ label_zone }}"
    }
   ]
  },
  {
   "title": "Pods distribution by Node provisioning model type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "sum by (label_provisioning_model) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_id=\"$DeploymentId\"})",
     "legendFormat": "{{ label_provisioning_model }}"
    }
   ]
  },
  {
   "title": "Pods distribution by Node instance type",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "sum by (label_node_instance_type) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_id=\"$DeploymentId\"})",
     "legendFormat": "{{ label_node_instance_type }}"
    }
   ]
  },
  {
   "title": "Filter by Service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods distribution by GCP zone",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum by (label_zone) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_service=\"$Service\"})",
       "legendFormat": "{{ label_zone }}"
      }
     ]
    },
    {
     "title": "Pods distribution by Node provisioning model type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 13 },
     "targets": [
      {
       "expr": "sum by (label_provisioning_model) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_service=\"$Service\"})",
       "legendFormat": "{{ label_provisioning_model }}"
      }
     ]
    },
    {
     "title": "Pods distribution by Node instance type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "sum by (label_node_instance_type) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_service=\"$Service\"})",
       "legendFormat": "{{ label_node_instance_type }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Filter by App",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Pods distribution by GCP zone",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "expr": "sum by (label_zone) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_app=\"$App\"})",
       "legendFormat": "{{ label_zone }}"
      }
     ]
    },
    {
     "title": "Pods distribution by Node provisioning model type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 14 },
     "targets": [
      {
       "expr": "sum by (label_provisioning_model) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_app=\"$App\"})",
       "legendFormat": "{{ label_provisioning_model }}"
      }
     ]
    },
    {
     "title": "Pods distribution by Node instance type",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 24 },
     "targets": [
      {
       "expr": "sum by (label_node_instance_type) (kube_pod_labels{clustername=\"${Cluster}\", namespace=\"${Namespace}\", label_app=\"$App\"})",
       "legendFormat": "{{ label_node_instance_type }}"
      }
     ]
    }
   ]
  }
 ]
}