{
 "title": "Redpanda Default Dashboard",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10m",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "Data Source", "query": "prometheus" },
   {
    "name": "node",
    "label": "Cluster",
    "query": {
     "query": "label_values(redpanda_application_uptime_seconds_total{}, instance)"
    }
   },
   { "name": "node_shard", "label": "Shard", "query": { "query": "label_values(shard)" } },
   {
    "name": "aggr_criteria",
    "label": "Aggregate by",
    "query": "Cluster : cluster,Instance : exported_instance,Instance\\,Shard : exported_instance\\,shard"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Redpanda Summary</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Topics (including internal topics)",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(redpanda_cluster_topics{instance=~\"$node\"})",
     "legendFormat": "topics count: "
    }
   ]
  },
  {
   "title": "Redpanda build information",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 4, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "group(redpanda_application_build{instance=~\"$node\"}) by (redpanda_version, redpanda_revision, [[aggr_criteria]])",
     "legendFormat": "{{exported_instance}} Version: {{redpanda_version}}, Revision: {{redpanda_revision}}"
    }
   ]
  },
  {
   "title": "Redpanda uptime in seconds",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 13, "x": 11, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (exported_instance, instance) (redpanda_application_uptime_seconds_total{instance=~\"$node\"})",
     "legendFormat": "broker: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Nodes Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redpanda_cluster_brokers{instance=~\"$node\"}",
     "legendFormat": "Nodes Up"
    }
   ]
  },
  {
   "title": "Latency of Kafka consume requests (p95) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"consume\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "P95: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Latency of Kafka consume requests (p99) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 8 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"consume\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "P99: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Partitions",
   "type": "stat",
   "gridPos": { "h": 6, "w": 2, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "redpanda_cluster_partitions{instance=~\"$node\"}",
     "legendFormat": "Partition count"
    }
   ]
  },
  {
   "title": "Latency of Kafka produce requests (p95) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 2, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"produce\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "P95: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Latency of Kafka produce requests (p99) per broker",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 14 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_kafka_request_latency_seconds_bucket{instance=~\"$node\", redpanda_request=\"produce\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "P99: {{exported_instance}}"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 0, "y": 20 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Internal RPC Latency</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 12, "x": 12, "y": 20 },
   "options": {
    "content": "<h1 style=\"color:#87CEEB; border-bottom: 3px solid #87CEEB;\">Throughput</h1>"
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "RPC latency (p95)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(redpanda_rpc_request_latency_seconds_bucket{instance=~\"$node\",redpanda_server=\"internal\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "broker: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "RPC latency (p99)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 22 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(redpanda_rpc_request_latency_seconds_bucket{instance=~\"$node\",redpanda_server=\"internal\"}[$__rate_interval])) by (le, $aggr_criteria))",
     "legendFormat": "broker: {{exported_instance}}"
    }
   ]
  },
  {
   "title": "Throughput of Kafka produce/consume requests for the cluster",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(redpanda_kafka_request_bytes_total[$__rate_interval])) by (redpanda_request)",
     "legendFormat": "redpanda_request: {{redpanda_request}}"
    }
   ]
  },
  {
   "title": "errors",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate - Total number of rest_proxy server errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_rest_proxy_request_errors_total{instance=~\"$node\"}[$__rate_interval])) by (redpanda_status)",
       "legendFormat": "redpanda_status: {{redpanda_status}}"
      }
     ]
    },
    {
     "title": "Rate - Number of rpc errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_rpc_request_errors_total{instance=~\"$node\"}[$__rate_interval])) by (redpanda_server)",
       "legendFormat": "redpanda_server: {{redpanda_server}}"
      }
     ]
    },
    {
     "title": "Rate - Total number of schema_registry server errors",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_schema_registry_request_errors_total{instance=~\"$node\"}[$__rate_interval])) by (redpanda_status)",
       "legendFormat": "redpanda_status: {{redpanda_status}}"
      }
     ]
    }
   ]
  },
  {
   "title": "io_queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate - Total read operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 78 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_io_queue_total_read_ops{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Rate - Total write operations passed in the queue",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 78 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_io_queue_total_write_ops{instance=~\"$node\"}[$__rate_interval])) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, class: {{class}}, ioshard: {{ioshard}}, mountpoint: {{mountpoint}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "memory",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Allocated memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_allocated_memory{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Total shard memory potentially available in bytes (free_memory plus reclaimable)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_available_memory{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "The low-water mark for available_memory from process start",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 79 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_available_memory_low_water_mark{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Free memory size in bytes",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 85 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_memory_free_memory{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Topic",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number of partitions in the cluster (replicas not included)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partitions{instance=~\"$node\"})",
       "legendFormat": "partitions count: "
      }
     ]
    },
    {
     "title": "Configured number of partitions for the topic",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "(avg(redpanda_kafka_partitions{instance=~\"$node\"}) by (redpanda_namespace, redpanda_topic))",
       "legendFormat": "redpanda_namespace: {{redpanda_namespace}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Configured number of replicas for the topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "avg(redpanda_kafka_replicas{instance=~\"$node\"}) by (redpanda_namespace, redpanda_topic)",
       "legendFormat": "redpanda_namespace: {{redpanda_namespace}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Amount of partitions that are moving from node",
     "type": "graph",
     "description": "can be agregated at instance level to show partitions moving from specific a specific node/broker",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partition_moving_from_node{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Amount of partitions that are moving to node",
     "type": "timeseries",
     "description": "can be agregated at instance level to show partitions moving to specific a specific node/broker",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partition_moving_to_node{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Amount of cancelling partition movements for node",
     "type": "graph",
     "description": "can be aggregated at instance level to show cancelling partition movements for a specific node/broker",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_partition_node_cancelling_movements{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Number of partitions that lack quorum among replicants",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_unavailable_partitions{instance=~\"$node\"})",
       "legendFormat": "partitions count: "
      }
     ]
    },
    {
     "title": "Number of under replicated replicas (i.e. replicas that are live, but not at the latest offest)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(redpanda_kafka_under_replicated_replicas{instance=~\"$node\"}) by (redpanda_namespace, redpanda_partition, redpanda_topic, $aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_partition: {{redpanda_partition}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Latest committed offset for the partition (i.e. the offset of the last message safely persisted on most replicas)",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_max_offset{instance=~\"$node\"}) by (redpanda_namespace, redpanda_topic, redpanda_partition)",
       "legendFormat": "redpanda_namespace: {{redpanda_namespace}}, redpanda_partition: {{redpanda_partition}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consumer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consumer group committed offset per topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_consumer_group_committed_offset{instance=~\"$node\"}) by (redpanda_group, redpanda_topic)",
       "legendFormat": "redpanda_group: {{redpanda_group}}, redpanda_partition: {{redpanda_partition}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Consumer group committed offset per topic, per partition",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_consumer_group_committed_offset{instance=~\"$node\"}) by (redpanda_group, redpanda_topic, redpanda_partition)",
       "legendFormat": "redpanda_group: {{redpanda_group}}, redpanda_partition: {{redpanda_partition}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Number of consumers in a group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 32 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_consumer_group_consumers{instance=~\"$node\"}) by (redpanda_group)",
       "legendFormat": "redpanda_group: {{redpanda_group}}"
      }
     ]
    },
    {
     "title": "Number of topics in a group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_consumer_group_topics{instance=~\"$node\"}) by (redpanda_group)",
       "legendFormat": "node: {{instance}}, redpanda_group: {{redpanda_group}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rate - Total number of bytes produced & consumed per topic",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "sum(rate(redpanda_kafka_request_bytes_total{instance=~\"$node\", redpanda_request=\"produce\"}[$__rate_interval])) by (redpanda_namespace, redpanda_request, redpanda_topic, $aggr_criteria)",
       "legendFormat": "Produce Throughput: broker: {{exported_instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_request: {{redpanda_request}}, redpanda_topic: {{redpanda_topic}}"
      },
      {
       "expr": "sum(rate(redpanda_kafka_request_bytes_total{instance=~\"$node\", redpanda_request=\"consume\"}[$__rate_interval])) by (redpanda_namespace, redpanda_request, redpanda_topic, $aggr_criteria)",
       "legendFormat": "Consume Throughput: broker: {{exported_instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_request: {{redpanda_request}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    }
   ]
  },
  {
   "title": "others",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Controller log rate limiting. Available rps for group",
     "type": "graph",
     "description": "Controller log rate limiting. Available rps for group, across all brokers",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_controller_log_limit_requests_available_rps{instance=~\"$node\"}) by (redpanda_cmd_group, $aggr_criteria)",
       "legendFormat": "redpanda_cmd_group: {{redpanda_cmd_group}}, broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Rate - Controller log rate limiting. Amount of requests that are dropped due to exceeding limit in group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 34 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_cluster_controller_log_limit_requests_dropped{instance=~\"$node\"}[$__rate_interval])) by (redpanda_cmd_group, $aggr_criteria)",
       "legendFormat": "redpanda_cmd_group: {{redpanda_cmd_group}}, broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Number of configured brokers in the cluster",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 34 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cluster_brokers{instance=~\"$node\"})",
       "legendFormat": "node: {{instance}}"
      }
     ]
    },
    {
     "title": "Total CPU busy time in seconds",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_cpu_busy_seconds_total{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "node: {{exported_instance}}, shard: {{shard}}"
      }
     ]
    },
    {
     "title": "Number of node status RPCs received by this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_node_status_rpcs_received{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Number of timed out node status RPCs from this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 40 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_node_status_rpcs_timed_out{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Internal latency of request for rest_proxy",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_rest_proxy_request_latency_seconds{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Number of node status RPCs sent by this node",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_node_status_rpcs_sent{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "RPC latency",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_rpc_request_latency_seconds{instance=~\"$node\"}) by (redpanda_server, $aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, redpanda_server: {{redpanda_server}}"
      }
     ]
    },
    {
     "title": "Count of currently active connections",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_rpc_active_connections{instance=~\"$node\"}) by (redpanda_server, $aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, redpanda_server: {{redpanda_server}}"
      }
     ]
    },
    {
     "title": "Internal latency of kafka produce requests",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 52 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_kafka_request_latency_seconds{instance=~\"$node\"}) by (redpanda_request, $aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, redpanda_request: {{redpanda_request}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Schema Registry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Internal latency of request for schema_registry",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(redpanda_schema_registry_request_latency_seconds_bucket{instance=~\"$node\"}[$__rate_interval])) by (le, [[aggr_criteria]]))",
       "legendFormat": "P95: broker: {{exported_instance}}"
      },
      {
       "expr": "histogram_quantile(0.99, sum(rate(redpanda_schema_registry_request_latency_seconds_bucket{instance=~\"$node\"}[$__rate_interval])) by (le, [[aggr_criteria]]))",
       "legendFormat": "P99: broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Rate of calls to Schema Registry",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum by ([[aggr_criteria]]) (rate(redpanda_schema_registry_request_latency_seconds_count{instance=~\"$node\"}[2m]))",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Total number of Schema Registry errors",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(redpanda_schema_registry_request_errors_total{instance=~\"$node\"}[2m])) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    }
   ]
  },
  {
   "title": "raft",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate - Number of leadership changes across all partitions of a given topic",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
     "yaxes": [
      { "format": "ops" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_raft_leadership_changes{instance=~\"$node\"}[$__rate_interval])) by (redpanda_namespace, redpanda_topic, $aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, redpanda_namespace: {{redpanda_namespace}}, redpanda_topic: {{redpanda_topic}}"
      }
     ]
    },
    {
     "title": "Bandwidth available for partition movement. bytes/sec",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "binBps" } },
     "yaxes": [
      { "format": "binBps" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_raft_recovery_partition_movement_available_bandwidth{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "scheduler",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Rate - Accumulated runtime of task queue associated with this scheduling group",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(rate(redpanda_scheduler_runtime_seconds_total{instance=~\"$node\"}[$__rate_interval])) by (redpanda_scheduling_group, $aggr_criteria)",
       "legendFormat": "node: {{exported_instance}}, redpanda_scheduling_group: {{redpanda_scheduling_group}}, shard: {{shard}}"
      }
     ]
    }
   ]
  },
  {
   "title": "storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Disk storage bytes free.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(redpanda_storage_disk_free_bytes{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Status of low storage space alert. 0-OK, 1-Low Space 2-Degraded",
     "type": "graph",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 44 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(redpanda_storage_disk_free_space_alert{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    },
    {
     "title": "Total size of attached storage, in bytes.",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(redpanda_storage_disk_total_bytes{instance=~\"$node\"}) by ($aggr_criteria)",
       "legendFormat": "broker: {{exported_instance}}"
      }
     ]
    }
   ]
  }
 ]
}