{
 "title": "Tardis Jobs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "Job name",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"},service_prometheus_track)"
    }
   },
   {
    "name": "by",
    "label": "by",
    "query": "job,kubernetes_pod_name,job\\,task_name,job\\,task_name\\,subtask_index"
   },
   {
    "name": "job_name_cmp",
    "label": "Compare With",
    "query": {
     "query": "query_result(count(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"}, \"job\", \"None-jobmanager\", \"job\", \".*\")) by (job) or count(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"}) by (job) or count(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"}, \"job\", \"Yesterday-jobmanager\", \"job\", \".*\")) by (job))"
    }
   },
   {
    "name": "jobmanager_job",
    "label": "Job Manager Job Tag",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-jobmanager|([[job_name_cmp]])-jobmanager\"},job)"
    }
   },
   {
    "name": "taskmanager_job",
    "label": "Task Manager Job Tag",
    "query": {
     "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-taskmanager|([[job_name_cmp]])-taskmanager\"},job)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job=~\"$taskmanager_job\"},task_name)"
    }
   },
   { "name": "func", "label": "func", "query": "max,avg" },
   {
    "name": "by_var",
    "query": "Job: {{job}}, Task: {{task_name}}, Pod: {{kubernetes_pod_name}}, Subtask: {{subtask_index}}"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flink Dashboard",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"$jobmanager_job\"}, \"dashboard\", \"http://$1.$2.$3.$4:8081\", \"host\", \"(.*)_(.*)_(.*)_(.*)\")) by (dashboard)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{job=~\"$jobmanager_job\"}",
     "legendFormat": "Registered {{job}}"
    },
    {
     "expr": "count(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Slots / TM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"} / flink_jobmanager_numRegisteredTaskManagers{job=~\"$jobmanager_job\"}"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"}",
     "legendFormat": "Total slots"
    },
    {
     "expr": "flink_jobmanager_taskSlotsAvailable{job=~\"$jobmanager_job\"}",
     "legendFormat": "Unused slots (should be 0)"
    }
   ]
  },
  {
   "title": "Avg Max Load [5m]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(max_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Task Subtasks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_job_task_numRecordsIn{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (job, task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Group Offset Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(redpanda_group) (max by(redpanda_namespace, redpanda_topic, redpanda_partition) (redpanda_kafka_max_offset{instance=~\"$redpanda_instance\", redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{instance=~\"$redpanda_instance\", redpanda_group=~\"[[redpanda_group]]\"})+1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total State Size (RockDB)",
   "type": "gauge",
   "description": "adding test explanation",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "SSTables: {{job}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Memtable: {{job}}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_Status_JVM_CPU_Load{job=~\"$jobmanager_job\"}) by (clustername)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Restarts ",
   "type": "stat",
   "description": "The total amount of full restarts of the job in the selected time period",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(flink_jobmanager_job_numRestarts{job=~\"$jobmanager_job\"}[30m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed records rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]]) or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m])) by ([[by]]) or on([[by]]) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]])  or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_spanner_change_stream_reader_DataRecordCount{job=~\"$taskmanager_job\"})) by ([[by]])",
     "legendFormat": "$by_var"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 1d) by ([[by]]) or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m] offset 1d)) by ([[by]]) or on([[by]]) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 1d) by ([[by]])  or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_spanner_change_stream_reader_DataRecordCount{job=~\"$taskmanager_job\"}) offset 1d) by ([[by]])",
     "legendFormat": "$by_var - <<$job_name_cmp>>"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "TM: {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "Average - {{job}}"
    }
   ]
  },
  {
   "title": "Resources",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU [AVG]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "avg(sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m] offset 1d)) by (job, kubernetes_pod_name)) by ([[by]])",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "CPU Throttling [MAX]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(max_over_time(rate(label_replace(label_replace(container_cpu_cfs_throttled_seconds_total{namespace=\"apache-flink\", pod=~\"$taskmanager_job.*\"}, \"job\", \"$1\", \"pod\", \"(.*-taskmanager)-.*\"), \"kubernetes_pod_name\", \"$1\", \"pod\", \"(.*)\")[1m])[5m])) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "max(max_over_time(rate(label_replace(label_replace(container_cpu_cfs_throttled_seconds_total{namespace=\"apache-flink\", pod=~\"$taskmanager_job.*\"}, \"job\", \"$1\", \"pod\", \"(.*-taskmanager)-.*\"), \"kubernetes_pod_name\", \"$1\", \"pod\", \"(.*)\")[1m] offset 1d)[5m])) by ([[by]])",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Heap Used [MAX]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "max(\n    max_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"$taskmanager_job\"}[2m]) / max_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Max{job=\"$taskmanager_job\"}[2m])\n) by ([[by]]) ",
       "legendFormat": "$by_var"
      },
      {
       "expr": "max(\n    max_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Used{job=\"$taskmanager_job\"}[2m]) offset 1d / max_over_time(flink_taskmanager_Status_JVM_Memory_Heap_Max{job=\"$taskmanager_job\"}[2m]) offset 1d\n) by ([[by]]) ",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Memory Capacity",
     "type": "stat",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "max(flink_taskmanager_Status_Flink_Memory_Managed_Total{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "Flink Managed ({{job}})"
      },
      {
       "expr": "max(flink_taskmanager_Status_JVM_Memory_Heap_Max{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "Heap ({{job}})"
      },
      {
       "expr": "max(flink_taskmanager_Status_JVM_Memory_Direct_TotalCapacity{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "Direct ({{job}})"
      }
     ]
    },
    {
     "title": "GC Rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_Status_JVM_GarbageCollector_All_Count{job=~\"$taskmanager_job\"}[2m])) by (job)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_Status_JVM_GarbageCollector_All_Count{job=~\"$taskmanager_job\"}[2m] offset 1d)) by (job)",
       "legendFormat": "{{job}} - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "GC Time Per Second",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_Status_JVM_GarbageCollector_All_Time{job=~\"$taskmanager_job\"}[2m])) by (job)",
       "legendFormat": "{{job}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_Status_JVM_GarbageCollector_All_Time{job=~\"$taskmanager_job\"}[2m] offset 1d)) by (job)",
       "legendFormat": "{{job}} - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Task Managers",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "count(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "Running ({{job}})"
      },
      {
       "expr": "sum(increase(flink_jobmanager_job_numRestarts{job=~\"$jobmanager_job\"}[1m])) by (job)",
       "legendFormat": "Restarts (right-y) ({{job}})"
      },
      {
       "expr": "count(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"} offset 1d) by (job)",
       "legendFormat": "Running ({{job}}) - <<$job_name_cmp>>"
      },
      {
       "expr": "sum(increase(flink_jobmanager_job_numRestarts{job=~\"$jobmanager_job\"}[1m])) by (job)",
       "legendFormat": "Restarts (right-y) ({{job}}) - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Task Slots",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"} - flink_jobmanager_taskSlotsAvailable{job=~\"$jobmanager_job\"}) by (job)",
       "legendFormat": "Used Slots ({{job}})"
      },
      {
       "expr": "sum(flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"}) by (job)",
       "legendFormat": "Total Slots ({{job}})"
      },
      {
       "expr": "sum(flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"} offset 1d - flink_jobmanager_taskSlotsAvailable{job=~\"$jobmanager_job\"} offset 1d) by (job)",
       "legendFormat": "Used Slots ({{job}}) - <<$job_name_cmp>>"
      },
      {
       "expr": "sum(flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"}) by (job)",
       "legendFormat": "Total Slots ({{job}}) - <<$job_name_cmp>>"
      }
     ]
    }
   ]
  },
  {
   "title": "Kafka",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Flink Source Total Lag",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job=~\"$taskmanager_job\"} >= 0) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_lag_max{job=~\"$taskmanager_job\"} >= 0) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Flink Source, Pending Records",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_pendingRecords{job=~\"$taskmanager_job\"} >= 0) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_pendingRecords{job=~\"$taskmanager_job\"} >= 0) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Consumed Rate, Records/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Consumed Rate, Bytes/s",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_bytes_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Kafka Fetch Avg Latency [MAX]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "max(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_fetch_latency_avg{job=~\"$taskmanager_job\"}) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "max(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_fetch_latency_avg{job=~\"$taskmanager_job\"}) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Assigned Partitions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_assigned_partitions{job=~\"$taskmanager_job\"}) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_assigned_partitions{job=~\"$taskmanager_job\"}) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Producer rate",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{job=~\"$taskmanager_job\"})) by ([[by]])",
       "legendFormat": "Records ($by_var)"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_error_total{job=~\"$taskmanager_job\"})) by ([[by]])",
       "legendFormat": "Errors ($by_var)"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_send_total{job=~\"$taskmanager_job\"})) by ([[by]]) offset 1d",
       "legendFormat": "Records ($by_var) - <<$job_name_cmp>>"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_KafkaProducer_record_error_total{job=~\"$taskmanager_job\"})) by ([[by]])",
       "legendFormat": "Errors ($by_var) - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Producer Send Time [AVG]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_currentSendTime{job=\"$taskmanager_job\"}) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "avg(flink_taskmanager_job_task_operator_currentSendTime{job=\"$taskmanager_job\"}) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    }
   ]
  },
  {
   "title": "Checkpoints",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "collapsed": true,
   "panels": [
    {
     "title": "Last checkpoint duration",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "dtdurationms" } },
     "targets": [
      {
       "expr": "avg(flink_jobmanager_job_lastCheckpointDuration{job=\"$jobmanager_job\"}) by (job)",
       "legendFormat": "$by_var"
      },
      {
       "expr": "avg(flink_jobmanager_job_lastCheckpointDuration{job=\"$jobmanager_job\"}) by (job) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Last checkpoint Size",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "avg(flink_jobmanager_job_lastCheckpointSize{job=\"$jobmanager_job\"}) by (job)",
       "legendFormat": "$by_var"
      },
      {
       "expr": "avg(flink_jobmanager_job_lastCheckpointSize{job=\"$jobmanager_job\"}) by (job) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Сheckpoint alignment time [$func]",
     "type": "timeseries",
     "description": "The time spent waiting to align checkpoints per task.",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 39 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "$func(flink_taskmanager_job_task_checkpointAlignmentTime{job=\"$taskmanager_job\"} > 0) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_checkpointAlignmentTime{job=\"$taskmanager_job\"} > 0) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "Checkpoint start delay time [$func]",
     "type": "timeseries",
     "description": "The maximum time spent waiting to start checkpointing per task.",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 39 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "$func(flink_taskmanager_job_task_checkpointStartDelayNanos{job=\"$taskmanager_job\"} > 0) by ([[by]])",
       "legendFormat": "$by_var"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_checkpointStartDelayNanos{job=\"$taskmanager_job\"} > 0) by ([[by]]) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasks Overview - $taskmanager_job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "repeat": "taskmanager_job",
   "collapsed": true,
   "panels": [
    {
     "type": "table",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 30 },
     "targets": [
      {
       "expr": "count(flink_taskmanager_job_task_numRecordsIn{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (job, task_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(avg_over_time(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by (job, task_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(avg_over_time(flink_taskmanager_job_task_busyTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by (job, task_name)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(avg_over_time(flink_taskmanager_job_task_numRecordsInPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by (job, task_name) / (min(avg_over_time(flink_taskmanager_job_task_numRecordsInPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by (job, task_name) + 1)",
       "legendFormat": "__auto"
      },
      {
       "expr": "max(avg_over_time(flink_taskmanager_job_task_numRecordsOutPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by (job, task_name) / (min(avg_over_time(flink_taskmanager_job_task_numRecordsOutPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by (job, task_name) + 1)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Tasks Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 },
   "collapsed": true,
   "panels": [
    {
     "title": "Subtasks",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "targets": [
      {
       "expr": "count(flink_taskmanager_job_task_numRecordsIn{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Back Pressure ms/sec [$func]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 0, "y": 30 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "$func(avg_over_time(flink_taskmanager_job_task_backPressuredTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Busy ms/sec [$func]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 8, "y": 30 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "$func(avg_over_time(flink_taskmanager_job_task_busyTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Idle Time ms/sec [$func]",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 8, "x": 16, "y": 30 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "avg(avg_over_time(flink_taskmanager_job_task_idleTimeMsPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Number Records In Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsInPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Number Records Out Per Second",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_numRecordsOutPerSecond{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Input Queue Length [$func]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 48 },
     "repeat": "func",
     "targets": [
      {
       "expr": "$func(avg_over_time(flink_taskmanager_job_task_buffers_inputQueueLength{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    },
    {
     "title": "Output Queue Length [$func]",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 48 },
     "repeat": "func",
     "targets": [
      {
       "expr": "$func(avg_over_time(flink_taskmanager_job_task_buffers_outputQueueLength{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}[5m])) by ([[by]], task_name)",
       "legendFormat": "$by_var"
      }
     ]
    }
   ]
  },
  {
   "title": "State",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total State Size (SSTables)",
     "type": "timeseries",
     "description": "adding test explanation",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job)",
       "legendFormat": "$by_var"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "State Size Per Task Manager (SStables) [$func]",
     "type": "timeseries",
     "description": "adding test explanation",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "$func(sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job, kubernetes_pod_name)) by (job)",
       "legendFormat": "$by_var"
      },
      {
       "expr": "$func(sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job, kubernetes_pod_name)) by (job) offset 1d",
       "legendFormat": "$by_var - <<$job_name_cmp>>"
      }
     ]
    },
    {
     "title": "State Read Latencies, p99 [$func]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [MapGet]"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [ValueGet]"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_listStateGetLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [ListGet]"
      }
     ]
    },
    {
     "title": "State Write Latencies, p99 [$func]",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
     "repeat": "func",
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [MapPut]"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [ValueUpdate]"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_listStateAddLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [ListAdd]"
      },
      {
       "expr": "$func(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency{job=~\"$taskmanager_job\", task_name=~\"$task_name\", quantile=\"0.99\"}) by ([[by]], state_name)",
       "legendFormat": "$by_var, State: {{state_name}} [MapPutAll]"
      }
     ]
    },
    {
     "title": "State Read Access Latencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateGetLatency ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStateGetLatency({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_listStateGetLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_listStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ListStateGetLatency ({{state_name}})"
      }
     ]
    },
    {
     "title": "State Read Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStateGetRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateGetRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateGetLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ListStateGetRate ({{state_name}})"
      }
     ]
    },
    {
     "title": "State Write Access Latencies",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "ns" } },
     "targets": [
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateUpdateLatency ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutAllLatency  ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (job, state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name, kubernetes_pod_name)) by (job, state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutLatency ({{state_name}})"
      },
      {
       "expr": "sum(avg(flink_taskmanager_job_task_operator_state_name_listStateAddLatency{job=~\"$taskmanager_job\", quantile=\"0.99\"}) by (state_name, kubernetes_pod_name) * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateAddLatency_count{job=\"$taskmanager_job\"}[1m])) by (state_name, kubernetes_pod_name)) by (state_name) / sum(rate(flink_taskmanager_job_task_operator_state_name_listStateAddLatency_count{job=\"$taskmanager_job\"}[1m])) by (state_name)",
       "legendFormat": "ListStateAddLatency ({{state_name}})"
      }
     ]
    },
    {
     "title": "State Write Rate",
     "type": "timeseries",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_valueStateUpdateLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ValueStateUpdateRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutAllLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutAllRate ({{state_name}}"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_mapStatePutLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "MapStatePutRate ({{state_name}})"
      },
      {
       "expr": "100 * sum(rate(flink_taskmanager_job_task_operator_state_name_listStateAddLatency_count{job=~\"$taskmanager_job\"}[1m])) by (job, state_name)",
       "legendFormat": "ListStateAddRate ({{state_name}})"
      }
     ]
    },
    {
     "title": "Active Compactions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_num_running_compactions{job=\"$taskmanager_job\"}) by (job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Active Flushes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_num_running_flushes{job=\"$taskmanager_job\"}) by (job)",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RocksDB Details",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 },
   "collapsed": true,
   "panels": [
    {
     "title": "Estimate RocksDb Keys",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_num_keys{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "{{column_family}}-{{job}}"
      }
     ]
    },
    {
     "title": "Estimate RocksDb Data Size",
     "type": "timeseries",
     "description": "total.sst.files.size + size.all.mem-tables",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}[1m]) by (column_family, job) \n+\nsum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}[1m]) by (column_family, job)",
       "legendFormat": "{{column_family}}-{{job}}"
      }
     ]
    },
    {
     "title": "RocksDB Block Cache",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_capacity{job=\"$taskmanager_job\"})",
       "legendFormat": "Capacity"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_usage{job=\"$taskmanager_job\"})",
       "legendFormat": "Usage"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_block_cache_pinned_usage{job=\"$taskmanager_job\"})",
       "legendFormat": "Pinned"
      }
     ]
    },
    {
     "title": "Estimate Pending Compaction Bytes Rate [1m] ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_estimate_pending_compaction_bytes{job=~\"$taskmanager_job\"}[1m])) by (column_family)",
       "legendFormat": "{{column_family}}"
      }
     ]
    },
    {
     "title": "Is Write Stopped",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "avg(flink_taskmanager_job_task_operator_column_family_rocksdb_is_write_stopped{job=~\"$taskmanager_job\"}[1m]) by (column_family, job)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Delayed Write Rate & Operator Stalls",
     "type": "timeseries",
     "description": "Stall micros - the duration of writer requiring to wait for compaction or flush to finish in RocksDB.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_actual_delayed_write_rate{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Delayed Write Rate - {{column_family}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_rocksdb_stall_micros{job=~\"$taskmanager_job\"}[1m])) by (operator_name, job)",
       "legendFormat": "Stall - {{operator_name}} (micros)"
      }
     ]
    },
    {
     "title": "Active Memtable Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Entries - {{column_family}}"
      }
     ]
    },
    {
     "title": "Active Memtable Deletes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Deletes - {{column_family}}"
      }
     ]
    },
    {
     "title": "Active Memtable Delete Ratio",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 101 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)\n/\nsum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_active_mem_table{job=~\"$taskmanager_job\"}[1m])) by (column_family, job)",
       "legendFormat": "Deletes ratio - {{column_family}}"
      }
     ]
    },
    {
     "title": "Unflushed Memtables",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 109 },
     "targets": [
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_num_immutable_mem_table{job=~\"$taskmanager_job\"}[1m]) by (job)",
       "legendFormat": "Unflushed - {{job}}"
      },
      {
       "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_mem_table_flush_pending{job=~\"$taskmanager_job\"}[1m]) by (job)",
       "legendFormat": "Flush pending - {{job}}"
      }
     ]
    },
    {
     "title": "Unflushed Memtable Entries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 109 },
     "targets": [
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_entries_imm_mem_tables{job=~\"$taskmanager_job\"}[1m])) by (job)",
       "legendFormat": "Entries - {{job}}"
      },
      {
       "expr": "sum(rate(flink_taskmanager_job_task_operator_column_family_rocksdb_num_deletes_imm_mem_tables{job=~\"$taskmanager_job\"}[1m])) by (job)",
       "legendFormat": "Deletes - {{job}}"
      }
     ]
    }
   ]
  }
 ]
}