{
 "title": "Feed relevance Service Dashboard",
 "description": "Service level monitoring",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "service", "label": "service:", "query": "feed-relevance-service" },
   {
    "name": "Path",
    "label": "Path",
    "query": {
     "query": "label_values(http_requests_total{service_prometheus_track=\"$service\"},route)"
    }
   },
   {
    "name": "language",
    "label": "Language",
    "query": "hindi, tamil, telugu, kannada, malayalam, gujarati, marathi, bengali, odia, punjabi, assamese, bhojpuri, haryanvi, rajasthani, urdu"
   },
   {
    "name": "service_prom_track",
    "label": "service_prom_track",
    "query": "feed-relevance-service, feed-relevance-service-canary"
   }
  ]
 },
 "panels": [
  { "title": "Dashboards", "type": "dashlist", "gridPos": { "h": 6, "w": 8, "x": 0, "y": 0 } },
  { "title": "Firing Alerts", "type": "alertlist", "gridPos": { "h": 6, "w": 8, "x": 8, "y": 0 } },
  {
   "title": "Error logs",
   "type": "text",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 0 },
   "options": {
    "content": "- [Error logs for FRS for the last 2 hours can be found in Kibana](http://logging-kibana.sharechat.internal:5601/app/discover#/view/81f965c0-30c5-11ee-a745-1f35ebd9f10f?_g=(filters%3A!()%2CrefreshInterval%3A(pause%3A!t%2Cvalue%3A0)%2Ctime%3A(from%3Anow-2h%2Fh%2Cto%3Anow))\n- ShareChat Production VPN required.\n- Only errors logged by the offical SC tracer client logger are shown in Kibana. Teltech logger etc., are not collected you need to check pod logs for those.\n- Pod logs can be accessed from K9s, Lens, or Kubectl. Grepping in logs is easy via Kubectl:\n   - `kubectl logs feed-relevance-service-canary-57d8ccb898-57b2q -n feed-relevance-service  | grep \"panic\"`"
   }
  },
  { "title": "Overview Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "HTTP Requests ${language} ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\", route=~\"[[Path]]\"}))by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "HTTP Non-2XXs ${language} in %",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\", route=~\"[[Path]]\", status!=\"2XX\"}))by (route)/\nsum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\", route=~\"[[Path]]\"}))by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Overall | P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"${service_prom_track}\"})) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Overall | P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"${service_prom_track}\"})) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Pod Restarts ${language}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=\"feed-relevance-service\", container=\"feed-relevance-service\"}))",
     "legendFormat": "Restarts"
    }
   ]
  },
  {
   "title": "Panics Count Rate ",
   "type": "timeseries",
   "description": "Rate of count of panics caught by middleware",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(panics_total{service_prometheus_track=\"${service_prom_track}\"})) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Pod Un-availability",
   "type": "timeseries",
   "description": "Rate of count of panics caught by middleware",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_unavailable{deployment=~\"feed-relevance-service.*\",clustername=\"sc-p-ds-generic-services-05\"}) by (deployment)",
     "legendFormat": "Unavailable - {{deployment}}"
    }
   ]
  },
  {
   "title": "Pod Availability",
   "type": "timeseries",
   "description": "Rate of count of panics caught by middleware",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"feed-relevance-service.*\",clustername=\"sc-p-ds-generic-services-05\"}) by (deployment)",
     "legendFormat": "Available - {{deployment}}"
    }
   ]
  },
  {
   "title": "Posts Ranked Per Request ${language}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(posts_ranked{service_prometheus_track=\"${service_prom_track}\"})) by (route) / sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\"})) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Number of Posts In Final Response Per Request ${language}",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(posts_in_final_response{service_prometheus_track=\"${service_prom_track}\", route=~\"[[Path]]\",kubernetes_pod_name=~\"feed-relevance-service-${language}.*\"})) by (service_prometheus_track, route) / on(route) group_left sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\", route=~\"[[Path]]\",kubernetes_pod_name=~\"feed-relevance-service-${language}.*\"})) by (service_prometheus_track, route)"
    }
   ]
  },
  {
   "title": "Ingress",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Ingress Request Volume",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "(sum(envoy::envoy_cluster_upstream_rq_total_irate_2m{envoy_cluster_name=~\"feed-relevance-service.*\"}) or vector(0)) + (sum(nginx_ingress::controller_requests_irate_2m{ingress=\"feed-relevance-service\"}) or vector(0))",
       "legendFormat": "feed-relevance-service"
      }
     ]
    },
    {
     "title": "Ingress Success Rate (non-4xx/5xx responses)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(\n  (sum(envoy::cluster_upstream_rq_irate_2m{envoy_response_code!~\"[4-5].*\",envoy_cluster_name=~\"feed-relevance-service.*\"}) or vector(0)) \n  + \n  (sum(nginx_ingress::controller_requests_rate_2m{ingress=\"feed-relevance-service\",status!~\"[4-5].*\"}) or vector(0))\n) \n/ \n(\n  (sum(envoy::cluster_upstream_rq_irate_2m{envoy_cluster_name=~\"feed-relevance-service.*\"}) or vector(0)) \n  + \n  (sum(nginx_ingress::controller_requests_rate_2m{ingress=\"feed-relevance-service\"}) or vector(1))\n)",
       "legendFormat": "feed-relevance-service"
      }
     ]
    },
    {
     "title": "QPS (Ingress Count)",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\", route!~\"(/trendingFeed)\"}))by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Requests without fallback posts (SLI)",
     "type": "timeseries",
     "description": "% of requests being served without fallback",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "(1-(sum(rate(fallback_responses_total{service_prometheus_track=\"${service_prom_track}\"})))/sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\"})))",
       "legendFormat": "Requests"
      }
     ]
    }
   ]
  },
  {
   "title": "Fallbacks - Error Counts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 53 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "% Requests served via Fallback ",
     "type": "timeseries",
     "description": "% Rate at which our apis are serving requests with some fallback in the path vs total requests",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(fallback_responses_total{service_prometheus_track=\"${service_prom_track}\", route!~\"(/preCompute|/getAlgoBasedCandidates|/getRankedPosts)\"}))by (route)/sum(rate(http_requests_total{service_prometheus_track=\"${service_prom_track}\", route!~\"(/preCompute|/getAlgoBasedCandidates|/getRankedPosts)\"}))by (route)",
       "legendFormat": "{{route}}"
      }
     ]
    },
    {
     "title": "Hystrix Fallback Rate % by Caller",
     "type": "timeseries",
     "description": "Rate of failures/total requests made via hystrix in given interval",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(hystrix_fallback_counter_aggregated{service_prometheus_track=\"${service_prom_track}\", callerId!~\".*Balancer.*\"})) by (callerId)/sum(rate(hystrix_request_counter_aggregated{service_prometheus_track=\"${service_prom_track}\", callerId!~\".*Balancer.*\"})) by (callerId)",
       "legendFormat": "{{callerId}}"
      }
     ]
    },
    {
     "title": "Hystrix Fallback Rate Count",
     "type": "timeseries",
     "description": "Total count of hystrix call fallbacks",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(rate(hystrix_fallback_counter_aggregated{service_prometheus_track=\"${service_prom_track}\", callerId!~\".*Balancer.*\"})) by (callerId)",
       "legendFormat": "{{callerId}}"
      }
     ]
    },
    {
     "title": "Hystrix Fallback Rate % by variant",
     "type": "timeseries",
     "description": "Rate of failures/total requests made via hystrix in given interval",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(hystrix_fallback_counter_aggregated{service=\"feed-relevance-service\", variant!~\".*no-ranker-cg.*\"})) by (variant) / sum(rate(hystrix_request_counter_aggregated{service=\"feed-relevance-service\", variant!~\".*no-ranker-cg.*\"})) by (variant)",
       "legendFormat": "{{variant}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Infrastructure",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU - used & requested",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "legendFormat": "__auto",
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "editorMode": "mql",
        "expr": "",
        "filters": [],
        "groupBys": [],
        "legendFormat": "__auto",
        "metricKind": "GAUGE",
        "metricType": "",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "fetch k8s_container\n| metric 'kubernetes.io/container/cpu/request_cores'\n| filter (resource.namespace_name == 'feed-relevance-service')\n| group_by 1m, [value_request_cores_mean: mean(value.request_cores)]\n| every 1m\n| group_by [],\n    [value_request_cores_mean_aggregate: aggregate(value_request_cores_mean)]",
        "range": true,
        "valueType": ""
       },
       "timeSeriesQuery": {
        "projectName": "prj-sc-p-ds-services",
        "query": "fetch k8s_container\n| metric 'kubernetes.io/container/cpu/request_cores'\n| filter (resource.namespace_name == 'feed-relevance-service')\n| group_by 1m, [value_request_cores_mean: mean(value.request_cores)]\n| every 1m\n| group_by [],\n    [value_request_cores_mean_aggregate: aggregate(value_request_cores_mean)]"
       }
      },
      {
       "timeSeriesQuery": {
        "projectName": "prj-sc-p-ds-services",
        "query": "fetch k8s_container\n| metric 'kubernetes.io/container/cpu/core_usage_time'\n| filter (resource.namespace_name == 'feed-relevance-service')\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_core_usage_time_aggregate: aggregate(value.core_usage_time)]"
       }
      }
     ]
    },
    {
     "title": "Memory - used & requested",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "legendFormat": "__auto",
       "metricQuery": {
        "aliasBy": "Requested",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "expr": "",
        "filters": [
         "resource.label.namespace_name",
         "=",
         "feed-relevance-service"
        ],
        "groupBys": [],
        "legendFormat": "__auto",
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/memory/request_bytes",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "fetch k8s_container\n| metric 'kubernetes.io/container/memory/request_bytes'\n| filter (resource.namespace_name == 'feed-relevance-service')\n| group_by 1m, [value_request_bytes_mean: mean(value.request_bytes)]\n| every 1m\n| group_by [],\n    [value_request_bytes_mean_aggregate: aggregate(value_request_bytes_mean)]",
        "range": true,
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "Used",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.namespace_name",
         "=",
         "feed-relevance-service"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/memory/used_bytes",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "fetch k8s_container\n| metric 'kubernetes.io/container/memory/used_bytes'\n| filter (resource.namespace_name == 'feed-relevance-service')\n| group_by 1m, [value_used_bytes_mean: mean(value.used_bytes)]\n| align rate(1m)\n| every 1m\n| group_by [],\n    [value_used_bytes_mean_aggregate: aggregate(value_used_bytes_mean)]",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Service Pod Throttling",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{clustername=~\"sc-p-ds-generic-services-05\", namespace=~\"${service_prom_track}\"}[5m]))\n/\nsum(rate(container_cpu_cfs_periods_total{clustername=~\"sc-p-ds-generic-services-05\", namespace=~\"${service_prom_track}\"}[5m]))",
       "legendFormat": "service_pod_throttling"
      }
     ]
    }
   ]
  }
 ]
}