{
 "title": "Feed Model Service Dashboard",
 "tags": [
  "sc-feed-content-journey",
  "service"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Model Age in Hours",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg(model_age{service=\"feed-model-service\", model_name!~\".*scylla.*\"}) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Resource Utilisation",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "Used Core %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "($A/$B)", "type": "math" }
     ]
    },
    {
     "title": "Used Memory %",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "($A/$B)", "type": "math" }
     ]
    },
    {
     "title": "Requests / Pod",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "targets": [
      { "expression": "($A)/$B", "type": "math" }
     ]
    },
    {
     "title": "Available pods",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=~\"feed-model-service.*\", clustername=~\"sc-p-ds-generic-services-05|sc-p-ds-generic-services-04\"}) by (route, clustername, deployment)",
       "legendFormat": "{{deployment}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Request Rate Distribution",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[1m])) by (route)\n/\nsum(rate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[1m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[1m])) by (route,status)",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "Request Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=~\"feed-model-service\"}[2m])) by (service_prometheus_track)",
     "legendFormat": "{{service_prometheus_track}}"
    }
   ]
  },
  {
   "title": "2XX Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"feed-model-service\", status=\"2XX\"}[1m])) by (status)/sum(rate(http_requests_total{service_prometheus_track=\"feed-model-service\"}[1m])) ",
     "legendFormat": "{{service_prometheus_track}}"
    }
   ]
  },
  {
   "title": "Z Score",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "(\n    (round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001))\n    -\n    (\n      quantile(0.5,\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 23h)\n          , \"offset\", \"1d\", \"\", \"\"\n        )\n        or\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 47h)\n          , \"offset\", \"2d\", \"\", \"\"\n        )\n        or\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 71h)\n          , \"offset\", \"3d\", \"\", \"\"\n        )\n        or\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 95h)\n          , \"offset\", \"4d\", \"\", \"\"\n        )\n        or\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 119h)\n          , \"offset\", \"5d\", \"\", \"\"\n        )\n        or\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 143h)\n          , \"offset\", \"6d\", \"\", \"\"\n        )\n        or\n        label_replace(\n          avg_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[2h] offset 167h)\n          , \"offset\", \"7d\", \"\", \"\"\n        )\n      )\n      without (offset)\n    )\n  )\n  /\n  (0.75 * stddev_over_time(round(sum(irate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\"}[2m])) by (ingress), 0.001)[123h]))\n",
     "legendFormat": "{{expression}}"
    }
   ]
  },
  {
   "title": "4XX Ingress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\".*\",controller_class=~\".*\",clustername=\"sc-p-ds-generic-services-05\",namespace=~\".*\",ingress=~\"feed-model-service\",status=~\"[4].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\".*\",controller_class=~\".*\",clustername=\"sc-p-ds-generic-services-05\",namespace=~\".*\",ingress=~\"feed-model-service\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "4XX Status",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"feed-model-service\", status=\"4XX\"}[1m])) by (status)/sum(rate(http_requests_total{service_prometheus_track=\"feed-model-service\"}[1m])) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "P99 Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"feed-model-service\"}[1m])) by (le,route)) ",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "P50 Latency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"feed-model-service\"}[1m])) by (le,route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "5XX Status",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"feed-model-service\", status=\"5XX\"}[1m])) by (status)/sum(rate(http_requests_total{service_prometheus_track=\"feed-model-service\"}[1m])) ",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "5XX Ingress",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{controller_pod=~\".*\",controller_class=~\".*\",clustername=\"sc-p-ds-generic-services-05\",namespace=~\".*\",ingress=~\"feed-model-service\",status=~\"[5].*\"}[2m])) by (ingress) / sum(rate(nginx_ingress_controller_requests{controller_pod=~\".*\",controller_class=~\".*\",clustername=\"sc-p-ds-generic-services-05\",namespace=~\".*\",ingress=~\"feed-model-service\"}[2m])) by (ingress)",
     "legendFormat": "{{ingress}}"
    }
   ]
  },
  {
   "title": "Pod Availability",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{namespace=\"feed-model-service\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "P90 Latency",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"feed-model-service\"}[1m])) by (le,route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Pod Restarts",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "topk(10, sum(increase(kube_pod_container_status_restarts_total{clustername=\"sc-p-ds-generic-services-05\", namespace=\"feed-model-service\"})) by (container))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "[Throughput] feed-model-service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=~\"feed-model-service\"}[2m])) by (service_prometheus_track)",
     "legendFormat": "{{service_prometheus_track}}"
    }
   ]
  },
  {
   "title": "Panic Count",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(panics_total{service_prometheus_track=\"feed-model-service\"}[2m])*120) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Pod Restart Rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 86 },
   "targets": [
    {
     "expr": "sum(rate(kube_pod_container_status_restarts_total{namespace=~\"feed-model-service\"}[10m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "DB Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Requests[total,read,write,other] for bdb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "$A/400000", "type": "math" },
      { "expression": "$C/400000", "type": "math" },
      { "expression": "$D/400000", "type": "math" }
     ]
    },
    {
     "title": "BDB: Used memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 116 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expression": "($A/$B)", "type": "math" }
     ]
    },
    {
     "title": "BDB: Ingress/Egress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "bdb_egress_bytes{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "Egress"
      },
      {
       "expr": "bdb_ingress_bytes{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "Ingress"
      }
     ]
    },
    {
     "title": "Avg latency for BDB",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 124 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "bdb_avg_latency{bdb=\"10275527\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}"
      },
      {
       "expr": "bdb_avg_write_latency{bdb=\"10275527\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "bdb_avg_write_latency"
      },
      {
       "expr": "bdb_avg_read_latency{bdb=\"10275527\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "bdb_avg_read_latency"
      },
      {
       "expr": "bdb_avg_other_latency{bdb=\"10275527\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "bdb_avg_other_latency"
      },
      {
       "expr": "max_over_time(bdb_avg_latency_max{bdb=\"10275527\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"})",
       "legendFormat": "bdb_avg_latency (max over $aggregation)"
      }
     ]
    },
    {
     "title": "BDB CPU utilization for bdb",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "expr": "bdb_main_thread_cpu_system{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"} + bdb_main_thread_cpu_user{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "main threads (masters)"
      },
      {
       "expr": "bdb_shard_cpu_system{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"} + bdb_shard_cpu_user{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "all threads (masters)"
      },
      {
       "expr": "bdb_fork_cpu_system{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"} + bdb_fork_cpu_user{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "all forks (masters)"
      },
      {
       "expr": "bdb_main_thread_cpu_system_max{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"} + bdb_main_thread_cpu_user_max{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "main threads max (masters)"
      },
      {
       "expr": "bdb_shard_cpu_system_max{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"} + bdb_shard_cpu_user_max{bdb=\"10275527\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}",
       "legendFormat": "all threads max (masters)"
      },
      {
       "expr": "sum((delta(redis_process_main_thread_cpu_system_seconds_total{bdb=\"10275527\",role=\"slave\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}[60s]) + delta(redis_process_main_thread_cpu_user_seconds_total{bdb=\"10275527\",role=\"slave\", cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}[60s]))/60)",
       "legendFormat": "Slave main threads"
      },
      {
       "expr": "sum((delta(redis_process_cpu_system_seconds_total{bdb=\"10275527\",role=\"slave\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"10275527\",role=\"slave\",cluster=\"c7942.asia-south1-mz.gcp.cloud.rlrcp.com\",clustername=~\"production-cluster-redis\"}[60s]))/60)",
       "legendFormat": "Slave all threads"
      }
     ]
    }
   ]
  },
  {
   "title": "Service Meta Monitoring",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Feature Service Errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(feature_service_errors_count{service_prometheus_track=\"feed-model-service\"}[1m])) by (route)",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Circuit Open Counter",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expression": "$ffm_feature_service_circuit_open/$ffm_requests",
     "type": "math"
    },
    {
     "expression": "$recent_events_service_circuit_open/$isp_requests",
     "type": "math"
    }
   ]
  },
  {
   "title": "Empty Response Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(empty_response_count{service_prometheus_track=\"feed-model-service\"}[1m])) by (route,model_type)",
     "legendFormat": "{{route}}-{{model_type}}"
    }
   ]
  },
  {
   "title": "P99 Latency By Model",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(latency_model_bucket{service_prometheus_track=\"feed-model-service\"}[1m])) by (le,modelName)) ",
     "legendFormat": "{{modelName}}"
    }
   ]
  },
  {
   "title": "Health Check Fails",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(failed_check_health{service_prometheus_track=\"feed-model-service\"}[1m])) by (status, method, route)",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "Empty User Embedding",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(user_embedding_empty{service_prometheus_track=\"feed-model-service\"}[1m])) by (model_name_prefix)",
     "legendFormat": "{{model_name_prefix}}"
    }
   ]
  },
  {
   "title": "Recent Event Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 121 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(recent_events_count{service_prometheus_track=\"feed-model-service\"}[1m])) by (model_type,event_name)",
     "legendFormat": "{{event_name}}-{{model_type}}"
    }
   ]
  },
  {
   "title": "Model Counter ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 121 },
   "targets": [
    {
     "expr": "sum(rate(model_counter{service_prometheus_track=\"feed-model-service\"}[1m])) by (model_name)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Recent Event Time Diff",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(recent_event_time_diff{service_prometheus_track=\"feed-model-service\"}[1m])) by (model_type))",
     "legendFormat": "{{model_type}}"
    }
   ]
  },
  {
   "title": "Missing User Embedding",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 129 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(failed_user_embs{service_prometheus_track=\"feed-model-service\"}[1m])) by (route,model_type)",
     "legendFormat": "{{route}}-{{model_type}}"
    }
   ]
  },
  {
   "title": "Canary",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 137 },
   "collapsed": true,
   "panels": [
    {
     "title": "Canary Total Request",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{service_prometheus_track=~\"feed-model-service\",id=\"feed-model-service-canary-tamil\"}[2m])) by (service_prometheus_track,id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Canary HTTP Status",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
     "targets": [
      {
       "expr": "sum(rate(http_requests_total{clustername=\"sc-p-ds-generic-services-05\",service_prometheus_track=~\"feed-model-service\",id=\"feed-model-service-canary-tamil\"}[1m])) by (id)",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Canary P99 Latency ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"feed-model-service\",id=\"feed-model-service-canary-tamil\"}[1m])) by (id,le)) ",
       "legendFormat": "{{id}}"
      }
     ]
    },
    {
     "title": "Canary P95 Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"feed-model-service\",id=\"feed-model-service-canary-tamil\"}[1m])) by (id,le)) ",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Pubsub",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 138 },
   "collapsed": true,
   "panels": [
    {
     "title": "Candidate Score Logging Pubsub",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 143 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "editorMode": "visual",
        "filters": [
         "resource.label.subscription_id",
         "=",
         "candidate-score-logging-to-bq"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "pubsub.googleapis.com/subscription/oldest_unacked_message_age",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "sharechat-production",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "FFM Feed Logging to Bq",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 143 },
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "",
        "alignmentPeriod": "cloud-monitoring-auto",
        "crossSeriesReducer": "REDUCE_NONE",
        "editorMode": "visual",
        "filters": [
         "resource.label.subscription_id",
         "=",
         "ffm-feed-score-logging-to-bq-v2"
        ],
        "groupBys": [],
        "metricKind": "GAUGE",
        "metricType": "pubsub.googleapis.com/subscription/oldest_unacked_message_age",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "sharechat-production",
        "query": "",
        "valueType": "INT64"
       }
      }
     ]
    }
   ]
  }
 ]
}