{
 "title": "Tardis Jobs",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   {
    "name": "job_name",
    "label": "Job name",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"},service_prometheus_track)"
    }
   },
   {
    "name": "by",
    "label": "by",
    "query": "job,kubernetes_pod_name,job\\,task_name,job\\,task_name\\,subtask_index"
   },
   {
    "name": "job_name_cmp",
    "label": "Compare With",
    "query": {
     "query": "query_result(count(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"}, \"job\", \"None-jobmanager\", \"job\", \".*\")) by (job) or count(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"}) by (job) or count(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"moj-.*\"}, \"job\", \"Yesterday-jobmanager\", \"job\", \".*\")) by (job))"
    }
   },
   {
    "name": "jobmanager_job",
    "label": "Job Manager Job Tag",
    "query": {
     "query": "label_values(flink_jobmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-jobmanager|([[job_name_cmp]])-jobmanager\"},job)"
    }
   },
   {
    "name": "taskmanager_job",
    "label": "Task Manager Job Tag",
    "query": {
     "query": "label_values(flink_taskmanager_Status_JVM_CPU_Load{job=~\"([[job_name]])-taskmanager|([[job_name_cmp]])-taskmanager\"},job)"
    }
   },
   {
    "name": "task_name",
    "label": "Task Name",
    "query": {
     "query": "label_values(flink_taskmanager_job_task_isBackPressured{job=~\"$taskmanager_job\"},task_name)"
    }
   },
   { "name": "func", "label": "func", "query": "max,avg" },
   {
    "name": "by_var",
    "query": "Job: {{job}}, Task: {{task_name}}, Pod: {{kubernetes_pod_name}}, Subtask: {{subtask_index}}"
   }
  ]
 },
 "panels": [
  { "title": "Main", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Flink Dashboard",
   "type": "table",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(label_replace(flink_jobmanager_Status_JVM_CPU_Load{job=~\"$jobmanager_job\"}, \"dashboard\", \"http://$1.$2.$3.$4:8081\", \"host\", \"(.*)_(.*)_(.*)_(.*)\")) by (dashboard)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Task Managers",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_numRegisteredTaskManagers{job=~\"$jobmanager_job\"}",
     "legendFormat": "Registered {{job}}"
    },
    {
     "expr": "count(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Slots / TM",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"} / flink_jobmanager_numRegisteredTaskManagers{job=~\"$jobmanager_job\"}"
    }
   ]
  },
  {
   "title": "Parallelism",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "flink_jobmanager_taskSlotsTotal{job=~\"$jobmanager_job\"}",
     "legendFormat": "Total slots"
    },
    {
     "expr": "flink_jobmanager_taskSlotsAvailable{job=~\"$jobmanager_job\"}",
     "legendFormat": "Unused slots (should be 0)"
    }
   ]
  },
  {
   "title": "Avg Max Load [5m]",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(sum(max_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Task Subtasks",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(flink_taskmanager_job_task_numRecordsIn{job=~\"$taskmanager_job\", task_name=~\"$task_name\"}) by (job, task_name)",
     "legendFormat": "{{task_name}}"
    }
   ]
  },
  {
   "title": "Kafka Consumer Group Offset Lag",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(redpanda_group) (max by(redpanda_namespace, redpanda_topic, redpanda_partition) (redpanda_kafka_max_offset{instance=~\"$redpanda_instance\", redpanda_namespace=\"kafka\", redpanda_topic=~\"[[redpanda_topic]]\"}) - on(redpanda_topic, redpanda_partition) group_right max by(redpanda_group, redpanda_topic, redpanda_partition)(redpanda_kafka_consumer_group_committed_offset{instance=~\"$redpanda_instance\", redpanda_group=~\"[[redpanda_group]]\"})+1)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total State Size (RockDB)",
   "type": "gauge",
   "description": "adding test explanation",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_total_sst_files_size{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "SSTables: {{job}}"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_column_family_rocksdb_size_all_mem_tables{job=~\"$taskmanager_job\"}) by (job)",
     "legendFormat": "Memtable: {{job}}"
    }
   ]
  },
  {
   "title": "Cluster",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(flink_jobmanager_Status_JVM_CPU_Load{job=~\"$jobmanager_job\"}) by (clustername)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Full Restarts ",
   "type": "stat",
   "description": "The total amount of full restarts of the job in the selected time period",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "sum(increase(flink_jobmanager_job_numRestarts{job=~\"$jobmanager_job\"}[30m]))",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Processed records rate",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "rps" } },
   "targets": [
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]]) or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m])) by ([[by]]) or on([[by]]) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"}) by ([[by]])  or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_spanner_change_stream_reader_DataRecordCount{job=~\"$taskmanager_job\"})) by ([[by]])",
     "legendFormat": "$by_var"
    },
    {
     "expr": "sum(flink_taskmanager_job_task_operator_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 1d) by ([[by]]) or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_pub_sub_project_PubSubPullMessagesCount{job=~\"$taskmanager_job\"}[5m] offset 1d)) by ([[by]]) or on([[by]]) sum(flink_taskmanager_job_task_operator_KafkaSourceReader_KafkaConsumer_records_consumed_rate{job=~\"$taskmanager_job\"} offset 1d) by ([[by]])  or on([[by]]) sum(rate(flink_taskmanager_job_task_operator_spanner_change_stream_reader_DataRecordCount{job=~\"$taskmanager_job\"}) offset 1d) by ([[by]])",
     "legendFormat": "$by_var - <<$job_name_cmp>>"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (kubernetes_pod_name)",
     "legendFormat": "TM: {{kubernetes_pod_name}}"
    },
    {
     "expr": "avg(sum(avg_over_time(flink_taskmanager_Status_JVM_CPU_Load{job=~\"$taskmanager_job\"}[5m])) by (job, kubernetes_pod_name)) by (job)",
     "legendFormat": "Average - {{job}}"
    }
   ]
  }
 ]
}