{
 "title": "Hamsa for ShareChat",
 "tags": [
  "ShareChat",
  "HAMSA",
  "sc-feed-content-journey"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "Cluster", "query": "sc-p-ds-generic-services-05" },
   { "name": "GcpProject", "query": "sharechat-production" },
   { "name": "RedisBdb", "query": "10820102" },
   {
    "name": "Path",
    "label": "path:",
    "query": {
     "query": "label_values(http_requests_total{service_prometheus_track=\"sharecone-service\"},route)"
    }
   },
   {
    "name": "Status",
    "label": "status:",
    "query": "200,400,404,429,499,500,502,503,504"
   },
   {
    "name": "IndexName",
    "label": "indexName:",
    "query": {
     "query": "label_values(hamsa_index_build_duration_seconds{service_prometheus_track=\"sharecone-index-builder\"}, indexName)"
    }
   },
   {
    "name": "TfService",
    "label": "TfService:",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"sharecone\", deployment=~\"hamsa-tf-service-.*\"}, deployment)"
    }
   },
   {
    "name": "IndexBuilder",
    "label": "IndexBuilder:",
    "query": {
     "query": "label_values(kube_deployment_status_replicas{namespace=\"sharecone\", deployment=~\"hamsa-index-builder-.*\"}, deployment)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "hamsa-api-overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Hamsa Api Total Request -Ds-generic-05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\",  route=~\"[[Path]]\",clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (route)",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api general view",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (route,status)",
     "legendFormat": "{{route}}-{{status}}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(nginx_ingress_controller_request_duration_seconds_bucket{ingress=\"sharecone-service\", status=~\"${Status}\"}[1m] offset 24h)) by (le, status))",
     "legendFormat": "{{status}}-1d-ago"
    }
   ]
  },
  {
   "title": "hamsa api total p99 latency (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"[[Path]]\", status=~\"[[Status]]\",clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (le,route,status,kubernetes_pod_name)))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "hamsa api total request rate",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m])) by (route,status)",
     "legendFormat": "{{route}}-{{status}}",
     "metricQuery": { "projectName": "sharechat-production" }
    },
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m] offset 24h)) by (route,status)",
     "legendFormat": "{{route}}-{{status}}-1d-ago"
    }
   ]
  },
  {
   "title": "Hamsa Api p99 ds-generic-service",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"[[Path]]\", status=~\"[[Status]]\",clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (le,route,status,kubernetes_pod_name)))",
     "legendFormat": "{{kubernetes_pod_name}}-{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api total p99 latency",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"[[Path]]\", status=~\"[[Status]]\"}[1m])) by (le,route,status))",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api total request rate (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m])) by (route,status,kubernetes_pod_name))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "topk_max(3, sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m])) by (route,status,kubernetes_pod_name))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "index wise metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {}
   ]
  },
  {
   "title": "hamsa api index wise request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_by_index_total{service_prometheus_track=\"sharecone-service\", status=~\"${Status}\", route=~\"${Path}\",indexName=~\"${IndexName}\", clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (route,indexName,status)",
     "legendFormat": "{{indexName}}-{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api index wise request rate (max)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 34 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(15, sum(rate(http_requests_by_index_total{service_prometheus_track=\"sharecone-service\", status=~\"${Status}\", route=~\"${Path}\", clustername=\"sc-p-ds-generic-services-05\"}[10m])) by (route,indexName,status))",
     "legendFormat": "{{indexName}}-{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api index wise p99 latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_by_index_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"${Path}\", status=~\"${Status}\",indexName=~\"${IndexName}\"}[1m])) by (le,route,indexName,status))",
     "legendFormat": "{{indexName}}-{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api index wise p99 latency (worst)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk_max(15, histogram_quantile(0.99, sum(rate(http_request_duration_by_index_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"${Path}\", status=~\"${Status}\"}[10m])) by (le,route,indexName,status)))",
     "legendFormat": "{{indexName}}-{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "index size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(size_of_index_present{service_prometheus_track=\"sharecone-index-builder\",indexName=~\"${IndexName}\"}) by (indexName)",
     "legendFormat": "{{indexName}}"
    }
   ]
  },
  {
   "title": "index size (largest)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 52 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(15, max(size_of_index_present{service_prometheus_track=\"sharecone-index-builder\"}) by (indexName))",
     "legendFormat": "{{indexName}}"
    }
   ]
  },
  {
   "title": "Recall Top 1000",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(recall_1000_index{indexName=~\"[[IndexName]]\"}) by (indexName)",
     "legendFormat": "{{indexName}}"
    }
   ]
  },
  {
   "title": "Recall Top 500",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(recall_500_index{indexName=~\"[[IndexName]]\"}) by (indexName)",
     "legendFormat": "{{IndexName}}"
    }
   ]
  },
  {
   "title": "sharecone-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 69 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Pod Wise Request - Ds-Generic",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", status=~\"[[Status]]\", route=~\"[[Path]]\",clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (route,status,kubernetes_pod_name))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "hamsa api total request rate (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m])) by (route,status,kubernetes_pod_name))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "topk_max(3, sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m])) by (route,status,kubernetes_pod_name))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "hamsa api total request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(http_requests_total{service_prometheus_track=\"sharecone-service\", status=~\"[[Status]]\", route=~\"[[Path]]\"}[1m])) by (route,status)",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api total p99 latency (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"[[Path]]\", status=~\"[[Status]]\"}[1m])) by (le,route,status,kubernetes_pod_name)))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "topk_max(3, histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", route=~\"[[Path]]\", status=~\"[[Status]]\", clustername=\"[[Cluster]]\"}[1m])) by (le,route,status,kubernetes_pod_name)))",
     "legendFormat": "{{route}}-{{status}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "hamsa api total p99 latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{service_prometheus_track=\"sharecone-service\", route=~\"[[Path]]\", status=~\"[[Status]]\",clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (le,route,status))",
     "legendFormat": "{{route}}-{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api 5xx responses",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"sharecone-service\", status=~\"[5].*\", clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (ingress, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "hamsa api 4xx responses",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 97 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(nginx_ingress_controller_requests{ingress=\"sharecone-service\", status=~\"[4].*\", clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (ingress, status)",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "sharecone-service container ram (sum by deployment) - sc-p-ds-generic-services-05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 97 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [used]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "sc-p-ds-generic-services-05",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=",
       "sharecone-service",
       "AND",
       "metric.label.memory_type",
       "=",
       "non-evictable"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "preprocessor": "none",
      "projectName": "$GcpProject",
      "query": "",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [requested]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "sc-p-ds-generic-services-05",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=",
       "sharecone-service"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_bytes",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "preprocessor": "none",
      "projectName": "$GcpProject",
      "query": "",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "sharecone-service container cpu cores (sum by deployment) - sc-p-ds-generic-services-05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [used]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "sc-p-ds-generic-service-05",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/cpu/core_usage_time",
      "perSeriesAligner": "ALIGN_RATE",
      "preprocessor": "none",
      "projectName": "$GcpProject",
      "query": "",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [requested]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "editorMode": "visual",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "sc-p-ds-generic-service-05",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "preprocessor": "none",
      "projectName": "$GcpProject",
      "query": "",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "Pod Available- Ds-generice-service-05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 105 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{clustername=\"sc-p-ds-generic-services-05\", namespace=\"sharecone\", deployment=\"sharecone-service\"}) by (deployment)"
    }
   ]
  },
  {
   "title": "Pod Restart - Ds-generics-service-05",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{clustername=\"sc-p-ds-generic-services-05\", namespace=\"sharecone\", container=\"sharecone-service\"}[5m])) by (container)"
    }
   ]
  },
  {
   "title": "sharecone-service pods restarts",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 113 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{clustername=\"[[Cluster]]\", namespace=\"sharecone\", container=\"sharecone-service\"}[5m])) by (container)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "sharecone-service go version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 121 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(go_info{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}) by (version)",
     "legendFormat": "{{ version }}"
    }
   ]
  },
  {
   "title": "sharecone-service heap size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 124 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sharecone-service-canary heap size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 124 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_heap_alloc_bytes{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "sharecone-service next GC trigger size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_next_gc_bytes{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_memstats_next_gc_bytes{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sharecone-service-canary next GC trigger size",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 133 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(go_memstats_next_gc_bytes{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "sharecone-service threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_threads{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_threads{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sharecone-service-canary threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 142 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_threads{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "sharecone-service goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "sum(go_goroutines{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m])",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sharecone-service-canary goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 151 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m]) by (kubernetes_pod_name)",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "sharecone-service gc pauses total latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 160 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_pauses_seconds_sum{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {
     "expr": "sum(rate(go_gc_pauses_seconds_sum{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[2m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "sharecone-service-canary gc pauses total latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 160 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "sum(rate(go_gc_pauses_seconds_sum{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[2m])) by (kubernetes_pod_name)",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "sharecone-service goroutine scheduling latency (p99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 169 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\"}[2m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{service_prometheus_track=\"sharecone-service\", id!=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[2m])) by (le))",
     "legendFormat": "Total"
    },
    { "expr": "go_tim", "legendFormat": "Total" }
   ]
  },
  {
   "title": "sharecone-service-canary goroutine scheduling latency (p99)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 169 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(go_sched_latencies_seconds_bucket{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[2m])) by (le, kubernetes_pod_name))",
     "legendFormat": "{{ kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "sharecone-service goroutines",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(go_goroutines{service_prometheus_track=\"sharecone-service\"}[1m])"
    }
   ]
  },
  {
   "title": "sharecone-service goroutines (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 178 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, sum(go_goroutines{service_prometheus_track=\"sharecone-service\"}[1m]) by (kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}}"
    },
    {
     "expr": "topk_max(3, sum(go_goroutines{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}[1m]) by (kubernetes_pod_name))",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "number of grpc connections available (by index-group, mink)",
   "type": "graph",
   "description": "Number of open GRPC connection pools  partitioned by index group",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(15, sum(-1 * grpc_connection_pool_available{service_prometheus_track=\"sharecone-service\"}) by (indexGroup)) * -1",
     "legendFormat": "{{indexGroup}}"
    }
   ]
  },
  {
   "title": "number of grpc connections available (by index-group, pod, mink)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 187 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, sum(-1 * grpc_connection_pool_available{service_prometheus_track=\"sharecone-service\"}) by (indexGroup, kubernetes_pod_name)) * -1",
     "legendFormat": "{{indexGroup}}-{{kubernetes_pod_name}}"
    },
    {
     "expr": "topk_max(5, sum(-1 * grpc_connection_pool_available{service_prometheus_track=\"sharecone-service\", id=\"sharecone-service-canary\", clustername=\"[[Cluster]]\"}) by (indexGroup, kubernetes_pod_name)) * -1",
     "legendFormat": "{{indexGroup}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "index-builder",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "hamsa index staleness",
     "type": "graph",
     "description": "number of seconds for which index is not being rebuilt in time",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(hamsa_index_staleness_seconds{service_prometheus_track=\"sharecone-index-builder\", indexName=~\".*\"}) by (indexName)",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "hamsa index staleness (worst)",
     "type": "graph",
     "description": "number of seconds for which index is not being rebuilt in time",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 4 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk_max(10, max(hamsa_index_staleness_seconds{service_prometheus_track=\"sharecone-index-builder\",indexName!~\"ads\",clustername=\"sc-p-ds-generic-jobs-01\"}) by (indexName))",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "hamsa index building duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(hamsa_index_build_duration_seconds{service_prometheus_track=\"sharecone-index-builder\", indexName=~\".*\"}) by (indexName)",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "hamsa index building duration (worst)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk_max(10, max(hamsa_index_build_duration_seconds{service_prometheus_track=\"sharecone-index-builder\"}) by (indexName))",
       "legendFormat": "{{indexName}}"
      },
      {
       "expr": "hamsa_index_build_duration_seconds{service_prometheus_track=\"sharecone-index-builder\"}"
      }
     ]
    },
    {
     "title": "Hamsa Index build Frequency",
     "type": "graph",
     "description": "plots last build time of all indices",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "max(time()-hamsa_index_build_time{service_prometheus_track=\"sharecone-index-builder\", indexName=~\".*\"}) by (indexName)",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "Hamsa Index build Frequency (worst)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 20 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "topk_max(10, max(time()-hamsa_index_build_time{service_prometheus_track=\"sharecone-index-builder\"}) by (indexName))",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "index-builder skipped vector count",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "max(hamsa_skipped_vector_count{service_prometheus_track=\"sharecone-index-builder\", indexName=~\".*\"}) by (indexName)",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "index-builder skipped vector count (worst)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 29 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk_max(10, max(hamsa_skipped_vector_count{service_prometheus_track=\"sharecone-index-builder\",clustername=\"sc-p-ds-generic-jobs-01\"}) by (indexName))",
       "legendFormat": "{{indexName}}"
      }
     ]
    },
    {
     "title": "index-builder container cpu cores (sum by deployment)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}} [used]",
        "alignmentPeriod": "+60s",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "sc-p-ds-generic-jobs-01",
         "AND",
         "resource.label.namespace_name",
         "=",
         "sharecone",
         "AND",
         "resource.label.container_name",
         "=~",
         "$IndexBuilder"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "CUMULATIVE",
        "metricType": "kubernetes.io/container/cpu/core_usage_time",
        "perSeriesAligner": "ALIGN_RATE",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "",
        "unit": "s{CPU}",
        "valueType": "DOUBLE"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}} [requested]",
        "alignmentPeriod": "+60s",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "$Cluster",
         "AND",
         "resource.label.namespace_name",
         "=",
         "sharecone",
         "AND",
         "resource.label.container_name",
         "=~",
         "$IndexBuilder"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/cpu/request_cores",
        "perSeriesAligner": "ALIGN_NEXT_OLDER",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "",
        "unit": "{cpu}",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "index-builder container ram (sum by deployment)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}} [used]",
        "alignmentPeriod": "+60s",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "sc-p-ds-generic-jobs-01",
         "AND",
         "resource.label.namespace_name",
         "=",
         "sharecone",
         "AND",
         "resource.label.container_name",
         "=~",
         "$IndexBuilder",
         "AND",
         "metric.label.memory_type",
         "=",
         "non-evictable"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/memory/used_bytes",
        "perSeriesAligner": "ALIGN_MEAN",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "",
        "unit": "By",
        "valueType": "INT64"
       }
      },
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}} [requested]",
        "alignmentPeriod": "+60s",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "sc-p-ds-generic-jobs-01",
         "AND",
         "resource.label.namespace_name",
         "=",
         "sharecone",
         "AND",
         "resource.label.container_name",
         "=~",
         "$IndexBuilder"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/memory/request_bytes",
        "perSeriesAligner": "ALIGN_NEXT_OLDER",
        "preprocessor": "none",
        "projectName": "prj-sc-p-ds-services",
        "query": "",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "index-builder pods availability",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{clustername=\"sc-p-ds-generic-jobs-01\", namespace=\"sharecone\", deployment=~\"[[IndexBuilder]]\"}) by (deployment)",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "index-builder pods restarts (worst)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(increase(kube_pod_container_status_restarts_total{clustername=\"sc-p-ds-generic-jobs-01\", namespace=\"sharecone\", container=~\"hamsa-index-builder-.*\"}[5m])) by (container))",
       "legendFormat": "{{deployment}}"
      }
     ]
    },
    {
     "title": "index-builder cpu throttling",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sharecone\", pod=~\"[[IndexBuilder]]-.*\"}[1m])) by (pod) / sum(rate(container_cpu_cfs_periods_total{namespace=\"sharecone\", pod=~\"[[IndexBuilder]]-.*\"}[1m])) by (pod)",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "index-builder cpu throttling (worst)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sharecone\", pod=~\"hamsa-index-builder-.*\"}[1m])) by (pod) / sum(rate(container_cpu_cfs_periods_total{namespace=\"sharecone\", pod=~\"hamsa-index-builder-.*\"}[1m])) by (pod))",
       "legendFormat": "{{pod}}"
      }
     ]
    }
   ]
  },
  {
   "title": "tf-service",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 },
   "targets": [
    {}
   ]
  },
  {
   "title": "tf-service index staleness",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 197 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "max(hamsa_index_staleness_seconds{service_prometheus_track=~\"[[TfService]]\",indexName!~\".*ads.*\"}) by (indexName)",
     "legendFormat": "{{indexName}}"
    }
   ]
  },
  {
   "title": "tf-service index staleness (worst)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 197 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "topk_max(10, max(hamsa_index_staleness_seconds{app=~\"hamsa-tf-service-.*\" , indexName!~\".*ads.*\"}) by (indexName))",
     "legendFormat": "{{indexName}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service index wise request rate",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:serving:request_count{namespace=\"sharecone\",clustername=\"sc-p-ds-generic-services-05\"}[1m])) by (model_name)",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Tf-Service Pod Availability - Ds-generic-Service-03",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 205 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{clustername=\"sc-p-ds-generic-services-05\", namespace=\"sharecone\", deployment=~\"[[TfService]]\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service index wise p99 latency",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 214 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(:tensorflow:serving:request_latency_bucket{clustername=\"sc-p-ds-generic-services-05\", service_prometheus_track=~\".*\",namespace=\"sharecone\"}[1m])) by (le, model_name))",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service index wise request rate (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 214 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk_max(15, sum(rate(:tensorflow:serving:request_count{service_prometheus_track=~\"[[TfService]]\"}[1m])) by (model_name, kubernetes_pod_name))",
     "legendFormat": "{{model_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service container cpu cores (sum by deployment)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 223 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [used]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "$TfService"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/cpu/core_usage_time",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$GcpProject",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [requested]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "$TfService"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "projectName": "$GcpProject",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "hamsa-tf-service [used total]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "hamsa-tf-service-.*"
      ],
      "groupBys": [],
      "metricKind": "CUMULATIVE",
      "metricType": "kubernetes.io/container/cpu/core_usage_time",
      "perSeriesAligner": "ALIGN_RATE",
      "projectName": "$GcpProject",
      "unit": "s{CPU}",
      "valueType": "DOUBLE"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "hamsa-tf-service [requested total]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "hamsa-tf-service-.*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/cpu/request_cores",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "projectName": "$GcpProject",
      "unit": "{cpu}",
      "valueType": "DOUBLE"
     }
    }
   ]
  },
  {
   "title": "sharecone-tf-service index wise p99 latency (by pod, topk)",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 223 },
   "yaxes": [
    { "format": "µs" }
   ],
   "targets": [
    {
     "expr": "topk_max(15, histogram_quantile(0.99, sum(rate(:tensorflow:serving:request_latency_bucket{clustername=\"[[Cluster]]\", service_prometheus_track=~\"[[TfService]]\"}[1m])) by (le, model_name, kubernetes_pod_name)))",
     "legendFormat": "{{model_name}}-{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service pods availability",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 231 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(kube_deployment_status_replicas_available{clustername=\"sc-p-ds-generic-services-05\", namespace=\"sharecone\", deployment=~\"[[TfService]]\"}) by (deployment)",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service container ram (sum by deployment)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 232 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [used]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "$TfService",
       "AND",
       "metric.label.memory_type",
       "=",
       "non-evictable"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$GcpProject",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "{{resource.label.container_name}} [requested]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "$TfService"
      ],
      "groupBys": [ "resource.label.container_name" ],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_bytes",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "projectName": "$GcpProject",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "hamsa-tf-service [used total]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "hamsa-tf-service-.*",
       "AND",
       "metric.label.memory_type",
       "=",
       "non-evictable"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/used_bytes",
      "perSeriesAligner": "ALIGN_MEAN",
      "projectName": "$GcpProject",
      "unit": "By",
      "valueType": "INT64"
     }
    },
    {
     "metricQuery": {
      "aliasBy": "hamsa-tf-service [requested total]",
      "alignmentPeriod": "+60s",
      "crossSeriesReducer": "REDUCE_SUM",
      "filters": [
       "resource.label.cluster_name",
       "=",
       "$Cluster",
       "AND",
       "resource.label.namespace_name",
       "=",
       "sharecone",
       "AND",
       "resource.label.container_name",
       "=~",
       "hamsa-tf-service-.*"
      ],
      "groupBys": [],
      "metricKind": "GAUGE",
      "metricType": "kubernetes.io/container/memory/request_bytes",
      "perSeriesAligner": "ALIGN_NEXT_OLDER",
      "projectName": "$GcpProject",
      "unit": "By",
      "valueType": "INT64"
     }
    }
   ]
  },
  {
   "title": "tf-service cpu throttling",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 239 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sharecone\",  deployment=~\"[[TfService]]\"}[1m])) by (pod) / sum(rate(container_cpu_cfs_periods_total{namespace=\"sharecone\", deployment=~\"[[TfService]]\"}[1m])) by (pod)",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sharecone\", exported_pod=~\"[[TfService]]-.*\"}[1m])) by (exported_pod) / sum(rate(container_cpu_cfs_periods_total{namespace=\"sharecone\", exported_pod=~\"[[TfService]]-.*\"}[1m])) by (exported_pod)",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "sharecone-tf-service pods restarts (worst)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 240 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(increase(kube_pod_container_status_restarts_total{namespace=\"sharecone\", container=~\"hamsa-tf-service-.*\",clustername=\"sc-p-ds-generic-services-05\"}[5m])) by (container))",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 247 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sharecone\",  deployment=~\"[[TfService]]\"}[1m])) by (pod) / sum(rate(container_cpu_cfs_periods_total{namespace=\"sharecone\",  deployment=~\"[[TfService]]\"}[1m])) by (pod))",
     "legendFormat": "{{pod}}"
    },
    {
     "expr": "topk(10, sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sharecone\", exported_pod=~\"hamsa-tf-service-.*\"}[1m])) by (exported_pod) / sum(rate(container_cpu_cfs_periods_total{namespace=\"sharecone\", exported_pod=~\"hamsa-tf-service-.*\"}[1m])) by (exported_pod))",
     "legendFormat": "{{exported_pod}}"
    }
   ]
  },
  {
   "title": "redis",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 255 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Vector search redis cpu",
     "type": "graph",
     "description": "Vector search redis cpu",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 6 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "(delta(redis_process_cpu_system_seconds_total{bdb=\"$RedisBdb\"}[60s]) + delta(redis_process_cpu_user_seconds_total{bdb=\"$RedisBdb\"}[60s]))/60*100 or redis_cpu_percent{bdb=\"$RedisBdb\"}"
      }
     ]
    },
    {
     "title": "Vector search redis memory",
     "type": "graph",
     "description": "Vector search redis memory",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 6 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "scalar(bdb_used_memory{bdb=\"10820102\"})/bdb_memory_limit{bdb=\"10820102\"}"
      }
     ]
    },
    {
     "title": "redis latency (p99)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(latency_redis_calls_bucket{service_prometheus_track=\"sharecone-service\", clustername=\"[[Cluster]]\"}[1m])) by (le,functionName,redisFunc))"
      }
     ]
    },
    {
     "title": "redis latency (p90)",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 14 },
     "yaxes": [
      { "format": "s" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(latency_redis_calls_bucket{service_prometheus_track=\"sharecone-service\", clustername=\"[[Cluster]]\"}[1m])) by (le,functionName,redisFunc))"
      }
     ]
    }
   ]
  },
  {
   "title": "k8s cluster overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 256 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "CPU",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{clustername=~\"sc-p-ds-generic-services-03|sc-p-ds-generic-jobs-01\", resource=\"cpu\"}) by (clustername)",
       "legendFormat": "{{clustername}}"
      }
     ]
    },
    {
     "title": "RAM",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_node_status_allocatable{clustername=~\"sc-p-ds-generic-services-03|sc-p-ds-generic-jobs-01\", resource=\"memory\"}) by (clustername)",
       "legendFormat": "{{clustername}}"
      }
     ]
    },
    {
     "title": "Hamsa TF Service - avg CPU utilization over pods",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 0, "y": 15 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}}",
        "alignmentPeriod": "stackdriver-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "$Cluster",
         "AND",
         "resource.label.pod_name",
         "=",
         "hamsa-tf-service*"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/cpu/request_utilization",
        "perSeriesAligner": "ALIGN_INTERPOLATE",
        "projectName": "sharechat-production",
        "query": "",
        "unit": "1",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Hamsa TF Service - total RAM over pods",
     "type": "graph",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 15 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}}",
        "alignmentPeriod": "stackdriver-auto",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "$Cluster",
         "AND",
         "resource.label.pod_name",
         "=",
         "hamsa-tf-service*"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/memory/used_bytes",
        "perSeriesAligner": "ALIGN_INTERPOLATE",
        "projectName": "sharechat-production",
        "query": "",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Hamsa TF Service - Pods delta within 1 hour period",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum_over_time(delta(kube_horizontalpodautoscaler_status_current_replicas{clustername=~\"[[Cluster]]\",namespace=~\"sharecone\",horizontalpodautoscaler=~\"hamsa-tf-service.*\"})[1h])",
       "legendFormat": "{{ horizontalpodautoscaler }}"
      }
     ]
    },
    {
     "title": "Hamsa TF Service - total Pods",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_horizontalpodautoscaler_status_current_replicas{clustername=~\"[[Cluster]]\",namespace=~\"sharecone\",horizontalpodautoscaler=~\"hamsa-tf-service.*\"}",
       "legendFormat": "{{ horizontalpodautoscaler }}"
      }
     ]
    },
    {
     "title": "Sharecone Service - avg CPU utilization over pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{resource.label.container_name}}",
        "alignmentPeriod": "stackdriver-auto",
        "crossSeriesReducer": "REDUCE_MEAN",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "$Cluster",
         "AND",
         "resource.label.pod_name",
         "=",
         "sharecone-service*"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/cpu/request_utilization",
        "perSeriesAligner": "ALIGN_INTERPOLATE",
        "projectName": "sharechat-production",
        "query": "",
        "unit": "1",
        "valueType": "DOUBLE"
       }
      }
     ]
    },
    {
     "title": "Sharecone Service - total RAM over pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "yaxes": [
      { "format": "bytes" }
     ],
     "targets": [
      {
       "metricQuery": {
        "aliasBy": "{{ resource.label.container_name }}",
        "alignmentPeriod": "stackdriver-auto",
        "crossSeriesReducer": "REDUCE_SUM",
        "editorMode": "visual",
        "filters": [
         "resource.label.cluster_name",
         "=",
         "$Cluster",
         "AND",
         "resource.label.pod_name",
         "=",
         "sharecone-service*",
         "AND",
         "metric.label.memory_type",
         "=",
         "non-evictable"
        ],
        "groupBys": [ "resource.label.container_name" ],
        "metricKind": "GAUGE",
        "metricType": "kubernetes.io/container/memory/used_bytes",
        "perSeriesAligner": "ALIGN_INTERPOLATE",
        "projectName": "sharechat-production",
        "query": "",
        "unit": "By",
        "valueType": "INT64"
       }
      }
     ]
    },
    {
     "title": "Sharecone Service - Pods",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 46 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_horizontalpodautoscaler_status_current_replicas{clustername=~\"[[Cluster]]\",namespace=~\"sharecone\",horizontalpodautoscaler=\"sharecone-service\"}) by (horizontalpodautoscaler)",
       "legendFormat": "{{ horizontalpodautoscaler }}"
      }
     ]
    },
    {
     "title": "Sharecone Pods - Failed or Unknown phase",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_status_phase{phase=~\"Failed|Unknown\",  namespace=\"sharecone\"}) by (phase, exported_pod) != 0",
       "legendFormat": "{{phase}}: {{ exported_pod }}}"
      }
     ]
    },
    {
     "title": "Sharecone Pods - Pending Phase",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 54 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(label_replace(\n  kube_pod_status_phase{phase=\"Pending\", clustername=\"[[Cluster]]\", namespace=\"sharecone\"}, \n  \"exported_pod_group\", \n  \"$1\", \n  \"exported_pod\",\n  \"(.*)-[^-]+-[^-]+$\"\n)) by (exported_pod_group)",
       "legendFormat": "{{ exported_pod_group }}"
      }
     ]
    },
    {
     "title": "Sharecone nodes by taints",
     "type": "graph",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 62 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "count(count(kube_node_spec_taint{clustername=~\"$Cluster\"}) by (key, node)) by (key) != 0",
       "legendFormat": "{{ key }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Post View Trigger Job",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 257 },
   "collapsed": true,
   "panels": [
    {
     "title": "Redpanda Hamsa  Insert Events",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 329 },
     "fieldConfig": { "defaults": { "unit": "wps" } },
     "targets": [
      {
       "expr": "sum(rate(redpanda_hamsa_insert_events_count{service_prometheus_track=\"post-view-trigger-job\" ,topic=\"hamsa-insert-events\"}[2m])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Pubsub Fallback Counter",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 329 },
     "targets": [
      {
       "expr": "sum(rate(pubsub_hamsa_insert_events_count{service_prometheus_track=\"post-view-trigger-job\",topic=\"hamsa-insert-events\"}[2m])) by (topic)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Zero Qualifying Indices",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 337 },
     "targets": [
      {
       "expr": "sum(rate(zero_qualifying_index_count{service_prometheus_track=\"post-view-trigger-job\"}[2m])) by (source,signal,ctype,lang)",
       "legendFormat": "{{source}}-{{signal}}-{{ctype}}-{{lang}}"
      }
     ]
    }
   ]
  }
 ]
}