{
 "title": "sc-recall-tf-service",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Namespace", "query": "sc-recall-tf-service" },
   {
    "name": "ModelGroup",
    "query": {
     "query": "label_values(:tensorflow:serving:request_count{kubernetes_namespace=\"$Namespace\"},app)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Request rate (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:serving:request_count{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Avg request rate (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "avg(rate(:tensorflow:serving:request_count{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Total loaded models (by model-group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(delta(rtfs_download_blob_time_count{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (remote_path, app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve latency p99 (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(:tensorflow:serving:request_latency_bucket{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve - models staleness",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "time() - min(:tensorflow:cc:saved_model:load_latency_by_stage_count:latest{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}) by (model_path)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve - input tensor bytes p99 (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(:tensorflow:core:graph_run_input_tensor_bytes_bucket{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve - output tensor bytes p99 (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(:tensorflow:core:graph_run_output_tensor_bytes_bucket{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve - input tensor bytes total (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:core:graph_run_input_tensor_bytes_sum{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve - output tensor bytes total  (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "binBps" } },
   "targets": [
    {
     "expr": "sum(rate(:tensorflow:core:graph_run_output_tensor_bytes_sum{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve - internal run latency p99 (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(:tensorflow:core:graph_run_time_usecs_histogram_bucket{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "TF-serve internal queue size p99 (by model group)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(:tensorflow:core:graph_pending_queue_length_histogram_bucket{kubernetes_namespace=\"$Namespace\", app=~\".*(${ModelGroup:pipe}).*\"}[5m])) by (app, le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "FRS - grpc pool connections in use (avg/max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg(rtfs_grpc_pool_capacity - rtfs_grpc_pool_available) by (model_group)",
     "legendFormat": "avg: {{model_group}}"
    },
    {
     "expr": "max(rtfs_grpc_pool_capacity - rtfs_grpc_pool_available) by (model_group)",
     "legendFormat": "max: {{model_group}}"
    }
   ]
  },
  {
   "title": "FRS - grpc pool capacity (min/max)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "min(rtfs_grpc_pool_capacity) by (model_group)",
     "legendFormat": "min: {{model_group}}"
    },
    {
     "expr": "max(rtfs_grpc_pool_capacity) by (model_group)",
     "legendFormat": "max: {{model_group}}"
    }
   ]
  },
  {
   "title": "rtfs total pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"sc-recall-tf-service\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_current_replicas{namespace=\"sc-recall-tf-service\"})",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "fms total pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_horizontalpodautoscaler_status_current_replicas{namespace=\"feed-model-service\"}",
     "legendFormat": "{{horizontalpodautoscaler}}"
    },
    {
     "expr": "sum(kube_horizontalpodautoscaler_status_current_replicas{namespace=\"feed-model-service\"})",
     "legendFormat": "total"
    }
   ]
  },
  {
   "title": "rtfs pods phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"sc-recall-tf-service\"}) by (phase)",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "fms pods phase",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kube_pod_status_phase{namespace=\"feed-model-service\"}) by (phase)",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "cpu throttling",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum(rate(container_cpu_cfs_throttled_periods_total{namespace=\"sc-recall-tf-service\"}[1m])) by (container) / \nsum(rate(container_cpu_cfs_periods_total{namespace=\"sc-recall-tf-service\"}[1m])) by (container)",
     "legendFormat": "{{horizontalpodautoscaler}}"
    }
   ]
  },
  {
   "title": "container restarts",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(kube_pod_container_status_restarts_total{ namespace=\"sc-recall-tf-service\"}[10m])) by (container)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}